#ifndef __AI_CLASSES_ID_H__
#define __AI_CLASSES_ID_H__
enum
{
	AILOGIC_BASE_VALUE	= 0x100f0000,
	AI_AI								= AILOGIC_BASE_VALUE + 1,
	AI_LOGIC						= AILOGIC_BASE_VALUE + 2,
	AI_INFANTRY					= AILOGIC_BASE_VALUE + 3,
	AI_AVIATION					= AILOGIC_BASE_VALUE + 4,
	AI_TANK							= AILOGIC_BASE_VALUE + 5,
	AI_TRANSPORT_UNIT		= AILOGIC_BASE_VALUE + 6,
	AI_SIMPLE_PATH_UNIT	= AILOGIC_BASE_VALUE + 8,

	AI_VIS_SHELL														= AILOGIC_BASE_VALUE + 11,
	AI_BURST_EXPLOSION											= AILOGIC_BASE_VALUE + 12,
	AI_MOMENT_CUMULATIVE_EXPL								= AILOGIC_BASE_VALUE + 13,
	AI_CUMULATIVE_EXPL											= AILOGIC_BASE_VALUE + 14,
	AI_BASE_GUN															= AILOGIC_BASE_VALUE + 15,
	AI_TURRET_GUN														= AILOGIC_BASE_VALUE + 16,
	AI_INVIS_SHELL													= AILOGIC_BASE_VALUE + 21,
																					
	AI_BEHAVIOUR_ANALYZER										= AILOGIC_BASE_VALUE + 22,
																					
	AI_COMMAND															= AILOGIC_BASE_VALUE + 23,
	AI_UNITS																= AILOGIC_BASE_VALUE + 24,
																					
	AI_EDITOR																= AILOGIC_BASE_VALUE + 25,
																					
	AI_SIMPLE_STATIC_OBJECT									= AILOGIC_BASE_VALUE + 26,
	AI_BUILDING															= AILOGIC_BASE_VALUE + 27,
	AI_STORAGE															= AILOGIC_BASE_VALUE + 28,
	

	AI_FAKE_BALLISTIC_TRAJ									= AILOGIC_BASE_VALUE + 29,
	AI_BOMB_BALLISTIC_TRAJ									= AILOGIC_BASE_VALUE + 30,
																					
	AI_ENTRENCHMENT_PART										= AILOGIC_BASE_VALUE + 31,
	AI_STANDART_PATH_FINDER									= AILOGIC_BASE_VALUE + 32,
	AI_PLANE_PATH_FINDER										= AILOGIC_BASE_VALUE + 33,
																					
	AI_FREE_OF_COLLISIONS										= AILOGIC_BASE_VALUE + 34,
	AI_GIVING_PLACE_COLLISIONS							= AILOGIC_BASE_VALUE + 35,
	AI_WAITING_COLLISION										= AILOGIC_BASE_VALUE + 36,
	AI_PLANE_COLLISION											= AILOGIC_BASE_VALUE + 37,
																					
	AI_STATIC_PATH													= AILOGIC_BASE_VALUE + 38,
	AI_STANDART_PATH												= AILOGIC_BASE_VALUE + 39,
	AI_STADART_DIR_PATH											= AILOGIC_BASE_VALUE + 40,
	AI_PLANE_PATH														= AILOGIC_BASE_VALUE + 42,
	AI_PLANE_SMOOTH_PATH										= AILOGIC_BASE_VALUE + 43,

	AI_SOLDIER_STATES_FACTORY								= AILOGIC_BASE_VALUE + 44,
	AI_SOLDIER_REST_STATE										= AILOGIC_BASE_VALUE + 45,
	AI_SOLDIER_ATTACK_STATE									= AILOGIC_BASE_VALUE + 46,
	AI_SOLDIER_MOVE_TO_STATE								= AILOGIC_BASE_VALUE + 47,
	AI_SOLDIER_TURN_TO_POINT_STATE					= AILOGIC_BASE_VALUE + 49,
	AI_SOLDIER_MOVE_BY_DIR_STATE						= AILOGIC_BASE_VALUE + 50,
	AI_SOLDIER_ENTER_STATE									= AILOGIC_BASE_VALUE + 51,
	AI_SOLDIER_ENTER_ENTRENCHMENT_STATE			= AILOGIC_BASE_VALUE + 52,
	AI_SOLDIER_SWARM_STATE									= AILOGIC_BASE_VALUE + 53,

	AI_IN_BUILDING_STATES_FACTORY						= AILOGIC_BASE_VALUE + 54,
	AI_SOLDIER_REST_IN_BUILDING_STATE				= AILOGIC_BASE_VALUE + 55,
	AI_SOLDIER_GO_OUT_STATE									= AILOGIC_BASE_VALUE + 56,

	AI_IN_ENTRENCHMENT_STATES_FACTORY				= AILOGIC_BASE_VALUE + 57,
	AI_SOLDIER_GO_OUT_ENTRENCHMENT_STATE		= AILOGIC_BASE_VALUE + 58,
	AI_SOLDIER_REST_IN_ENTRENCHMENT_STATE		= AILOGIC_BASE_VALUE + 59,
	AI_SOLDIER_ATTACK_IN_ENTRENCH_STATE			= AILOGIC_BASE_VALUE + 60,

	AI_IN_TRANSPORT_STATES_FACTORY					= AILOGIC_BASE_VALUE + 61,
	AI_SOLDIER_REST_ON_BOARD_STATE					= AILOGIC_BASE_VALUE + 62,

	AI_PLANE_STATES_FACTORY									= AILOGIC_BASE_VALUE + 63,
	AI_PLANE_REST_STATE											= AILOGIC_BASE_VALUE + 64,
	AI_PLANE_BOMB_STATE											= AILOGIC_BASE_VALUE + 65,

	AI_TANK_STATES_FACTORY									= AILOGIC_BASE_VALUE + 67,

	AI_TRANSPORT_STATES_FACTORY							= AILOGIC_BASE_VALUE + 68,
	AI_TRANSPORT_WAIT_PASSENGER_STATE				= AILOGIC_BASE_VALUE + 69,
	AI_TRANSPORT_LAND_STATE									= AILOGIC_BASE_VALUE + 70,

	AI_ENTRENCHMENT													= AILOGIC_BASE_VALUE + 71,

	AI_FORMATION														= AILOGIC_BASE_VALUE + 74,
	AI_FORMATION_STATES_FACTORY							= AILOGIC_BASE_VALUE + 75,
	AI_FORMATION_REST_STATE									= AILOGIC_BASE_VALUE + 76,
	AI_FORMATION_MOVE_TO_STATE							= AILOGIC_BASE_VALUE + 77,
	AI_FORMATION_ENTER_BUILDING_STATE				= AILOGIC_BASE_VALUE + 78,
	AI_FORMATION_ENTER_ENTRENCHMENT_STATE		= AILOGIC_BASE_VALUE + 79,
	AI_FORMATION_IDLE_BUILDING_STATE				= AILOGIC_BASE_VALUE + 80,
	AI_FORMATION_IDLE_ENTRENCHMENT_STATE		= AILOGIC_BASE_VALUE + 81,
	AI_FORMATION_LEAVE_BUILDING_STATE				= AILOGIC_BASE_VALUE + 82,
	AI_FORMATION_LEAVE_ENTRENCHMNENT_STATE	= AILOGIC_BASE_VALUE + 83,
	AI_FORMATION_PLACE_MINE									= AILOGIC_BASE_VALUE + 84,
	AI_FORMATION_CLEAR_MINE									= AILOGIC_BASE_VALUE + 85,
	AI_FORMATION_ATTACK_UNIT_STATE					= AILOGIC_BASE_VALUE + 86,
	AI_FORMATION_ATTACK_COMMON_STAT_OBJ_STATE	= AILOGIC_BASE_VALUE + 87,

	AI_SOLDIER_PARADE_STATE									= AILOGIC_BASE_VALUE + 88,
	AI_SOLDIER_PLACE_MINE_NOW_STATE					= AILOGIC_BASE_VALUE + 89,
	AI_SOLDIER_CLEAR_MINE_RADIUS_STATE			= AILOGIC_BASE_VALUE + 90,
	
	AI_UNIT_GUN_DESCRIPTOR									= AILOGIC_BASE_VALUE + 91,

	AI_SOLDIER_ATTACK_COMMON_STAT_OBJ_STATE	= AILOGIC_BASE_VALUE + 92,
	AI_COMMON_SWARM_STATE										= AILOGIC_BASE_VALUE + 93,

	AI_BRIDGE_SPAN													= AILOGIC_BASE_VALUE + 95,
	AI_ANTI_ARTILLERY												= AILOGIC_BASE_VALUE + 96,
	AI_INSTALL_STATE												= AILOGIC_BASE_VALUE + 97,
	AI_UNINSTALL_STATE											= AILOGIC_BASE_VALUE + 98,

	AI_ARTILLERY_STATES_FACTORY							= AILOGIC_BASE_VALUE + 99,
	AI_ARTILLERY_MOVE_TO_STATE							= AILOGIC_BASE_VALUE + 100,
	AI_ARTILLERY_TURN_TO_POINT_STATE				= AILOGIC_BASE_VALUE + 101,
	AI_ARTILLERY_BOMBARDMENT_STATE					= AILOGIC_BASE_VALUE + 102,
	AI_ARTILLERY_RANGE_AREA_STATE						= AILOGIC_BASE_VALUE + 103,
	AI_ARTILLERY														= AILOGIC_BASE_VALUE + 104,

	AI_ART_ROCKET_STATES_FACTORY						= AILOGIC_BASE_VALUE + 105,
	AI_ART_ROCKET_ATTACK_GROUND_STATE				= AILOGIC_BASE_VALUE + 106,
	AI_ROCKET_REST_STATE										= AILOGIC_BASE_VALUE + 107,

	AI_COMMON_ATTACK_UNIT_IN_BUILDING_STATE	= AILOGIC_BASE_VALUE + 108,
	AI_SOLDIER_ATTACK_UNIT_IN_BUILDING_STATE = AILOGIC_BASE_VALUE + 109,
	AI_FORMATION_ATTACK_UNIT_IN_BUILDING_STATE = AILOGIC_BASE_VALUE + 110,

	AI_COMMON_AMBUSH_STATE									= AILOGIC_BASE_VALUE + 111,
	AI_MINE																	= AILOGIC_BASE_VALUE + 112,
	AI_SMOOTH_PATH_MEMENTO									= AILOGIC_BASE_VALUE + 113,

	AI_FORMATION_ROTATE_STATE								= AILOGIC_BASE_VALUE + 114,

	AI_UNIT_TURRET													= AILOGIC_BASE_VALUE + 115,
	AI_MOUNTED_TURRET												= AILOGIC_BASE_VALUE + 116,

	AI_MOUNTED_GUN													= AILOGIC_BASE_VALUE + 117,

	AI_SOLDIER_ATTACK_IN_BUILDING_STATE			= AILOGIC_BASE_VALUE + 122,

	AI_FORMATION_ENTER_TRANSPORT_STATE			= AILOGIC_BASE_VALUE + 123,
	AI_FORMATION_IDLE_TRANSPORT_STATE				= AILOGIC_BASE_VALUE + 124,

	AI_SOLDIER_ENTER_TRANSPORT_NOW_STATE		= AILOGIC_BASE_VALUE + 125,
	AI_SOLDIER_PARADROP_STATE								= AILOGIC_BASE_VALUE + 126,

	AI_PLANE_PARADRP_STATE									= AILOGIC_BASE_VALUE + 127,
	AI_PLANE_FIGHTER_PATROL_STATE						= AILOGIC_BASE_VALUE + 128,
	AI_PLANE_LEAVE_STATE										= AILOGIC_BASE_VALUE + 129,
	AI_PARATROOPER_PATH											= AILOGIC_BASE_VALUE + 130,
	
	AI_FORMATION_ENTER_TRANSPORT_NOW_STATE	= AILOGIC_BASE_VALUE + 131,

	AI_FORMATION_CATCH_TRANSPORT_STATE			= AILOGIC_BASE_VALUE + 132,
	AI_FORMATION_PARADROP_STATE							= AILOGIC_BASE_VALUE + 133,

	AI_TRANSPORT_REPAIR_STATE								= AILOGIC_BASE_VALUE + 134,
	AI_TRANSPORT_RESUPPLY_STATE							= AILOGIC_BASE_VALUE + 135,
	AI_TRANSPORT_ENTRENCH_STATE							= AILOGIC_BASE_VALUE + 136,

	AI_TRANSPORT_BUILDFENCE_STATE						= AILOGIC_BASE_VALUE + 137,
	AI_FORMATION_BUILD_LONGOBJECT_STATE			= AILOGIC_BASE_VALUE + 138,
	AI_TRANSPORT_ENTRENCHMENT_STATE					= AILOGIC_BASE_VALUE + 139,
	
	AI_FORMATION_REPAIR_UNIT_STATE					= AILOGIC_BASE_VALUE + 140,
	AI_FORMATION_RESUPPLY_UNIT_STATE				= AILOGIC_BASE_VALUE + 141,
	AI_SMOKE_SCREEN													= AILOGIC_BASE_VALUE + 142,
	AI_FORMATION_PLACE_ANTITANK_STATE				= AILOGIC_BASE_VALUE + 143,
	

	AI_CATCH_FORMATION_STATE								= AILOGIC_BASE_VALUE + 144,
	AI_FORMATION_BUILD_FENCE_STATE					= AILOGIC_BASE_VALUE + 145,
	AI_FORMATION_BUILD_ENTRENCH_STATE				= AILOGIC_BASE_VALUE + 146,
	AI_FORMATION_GUNSERVE_STATE							= AILOGIC_BASE_VALUE + 147,

	AI_ENTRENCHMENT_TANKPIT									= AILOGIC_BASE_VALUE + 148,
	
	AI_MECH_UNIT_GUNS												= AILOGIC_BASE_VALUE + 149,
	AI_INFANTRY_GUNS												= AILOGIC_BASE_VALUE + 150,
	AI_COMMON_GUN_INFO											= AILOGIC_BASE_VALUE + 151,
	
	AI_RU_CONTAINER													= AILOGIC_BASE_VALUE + 152,
	AI_ARTILLERY_BULLET_STORAGE							= AILOGIC_BASE_VALUE + 153,
	
	AI_FORMATION_ATTACK_FORMATION_STATE			= AILOGIC_BASE_VALUE + 154,
	AI_FORMATION_USE_SPYGLASS_STATE					= AILOGIC_BASE_VALUE + 155,

	AI_SOLDIER_USE_SPYGLASS_STATE						= AILOGIC_BASE_VALUE + 156,
	AI_SOLDIER_ATTACK_FORMATION_STATE				= AILOGIC_BASE_VALUE + 157,
	
	AI_FORMATION_PARADE_STATE								= AILOGIC_BASE_VALUE + 158,
	AI_ARTILLERY_CREW_PATH									= AILOGIC_BASE_VALUE + 159,

	AI_TRANSPORT_HOOK_ARTILLERY_STATE				= AILOGIC_BASE_VALUE + 162,
	AI_ARTILLERY_BEING_TOWED_STATE					= AILOGIC_BASE_VALUE + 163,
	AI_TRANSPORT_UNHOOK_ARTILLERY_STATE			= AILOGIC_BASE_VALUE + 164,
	AI_FORMATION_CAPTURE_ARTILLERY_STATE		= AILOGIC_BASE_VALUE + 165,
	
	AI_DEAD_UNIT														= AILOGIC_BASE_VALUE + 166,
	AI_BALLISTIC_TRAJ												= AILOGIC_BASE_VALUE + 167,
	AI_TRAIN_SMOOTH_PATH_MEMENTO						= AILOGIC_BASE_VALUE + 168,
	
	AI_TANK_LEAVE_TANKPIT_STATE							= AILOGIC_BASE_VALUE + 169,
	AI_TANK_TANKPIT_PATH										= AILOGIC_BASE_VALUE + 170,
	AI_PLANE_SHTURMOVIK_PATROL_STATE				= AILOGIC_BASE_VALUE + 171,
	
	AI_SOLDIER_IDLE_STATE										= AILOGIC_BASE_VALUE + 172,
	AI_FULL_ENTRENCHMENT										= AILOGIC_BASE_VALUE + 173,
	AI_ARTILLERY_BEING_TOWED_PATH						= AILOGIC_BASE_VALUE + 174,

	AI_TANK_PRESIZE_PATH										= AILOGIC_BASE_VALUE + 175,
	AI_FORMATION_LOAD_RU_STATE							= AILOGIC_BASE_VALUE + 176,
	
	AI_GIVING_PLACE_ROTATE_COLLISION				= AILOGIC_BASE_VALUE + 177,
	AI_STOP_COLLISION												= AILOGIC_BASE_VALUE + 178,
	AI_SOLDIER_ATTACK_AVIATION_STATE				= AILOGIC_BASE_VALUE + 179,
	AI_FOLLOW_STATE													= AILOGIC_BASE_VALUE + 180,
	
	AI_FULL_BRIDGE													= AILOGIC_BASE_VALUE + 181,
	
	AI_FORMATION_DISBAND_STATE							= AILOGIC_BASE_VALUE + 182,
	AI_FORMATION_FORM_STATE									= AILOGIC_BASE_VALUE + 183,
	AI_FORMATION_WAIT_TO_FORM_STATE					= AILOGIC_BASE_VALUE + 184,
	
	AI_ARTILLERY_ATTACK_STATE								= AILOGIC_BASE_VALUE + 185,
	AI_ARTILLERY_ATTACK_COMMON_STAT_OBJ_STATE	= AILOGIC_BASE_VALUE + 186,
	AI_ARTILLERY_REST_STATE									= AILOGIC_BASE_VALUE + 187,
	AI_ARTILLERY_ATTACK_AVIATION_STATE			= AILOGIC_BASE_VALUE + 188,
	AI_TARNSPORT_RESUPPLY_HUMAN_RESOURCES_STATE = AILOGIC_BASE_VALUE + 189,
	AI_TRANSPORT_LOAD_RU_STATE							= AILOGIC_BASE_VALUE + 190,
	AI_PLANE_SCOUT_STATE										= AILOGIC_BASE_VALUE + 191,

	AI_SNIPER																= AILOGIC_BASE_VALUE + 192,
	
	AI_FORMATION_SWARM_STATE								= AILOGIC_BASE_VALUE + 193,
	AI_MECH_ATTACK_UNIT_STATE								= AILOGIC_BASE_VALUE + 194,

	AI_TANK_SHOOT_ESTIMATOR									= AILOGIC_BASE_VALUE + 195,
	AI_SOLDIER_SHOOT_ESTIMATOR							= AILOGIC_BASE_VALUE + 196,
	AI_PLANE_DEFFENSIVE_SHOOT_ESTIMATOR			= AILOGIC_BASE_VALUE + 197,
	AI_SHTURMOVIK_SHOOT_ESTIMATOR						= AILOGIC_BASE_VALUE + 198,
	
	AI_HIT_INFO															= AILOGIC_BASE_VALUE + 199,

	AI_FENCE																= AILOGIC_BASE_VALUE + 200,
	
	AI_TRAIN_PATH														= AILOGIC_BASE_VALUE + 201,
	AI_TRAIN_SMOOTH_PATH										= AILOGIC_BASE_VALUE + 202,

	AI_TRAIN_PATH_UNIT											= AILOGIC_BASE_VALUE + 203,

	AI_EDGE_POINT														= AILOGIC_BASE_VALUE + 204,
	AI_SPLINE_EDGE													= AILOGIC_BASE_VALUE + 205,
	AI_RAILROAD															= AILOGIC_BASE_VALUE + 206,

	AI_TRAIN_PATH_FINDER										= AILOGIC_BASE_VALUE + 207,

	AI_ZERO_EDGE														= AILOGIC_BASE_VALUE + 208,
	AI_CARRIAGE_PATH_UNIT										= AILOGIC_BASE_VALUE + 209,


	AI_SOLDIER_HULLDOWN_STATE								= AILOGIC_BASE_VALUE + 210,
	AI_SOLDIER_FIREMORALESHELL_STATE				= AILOGIC_BASE_VALUE + 211,

	AI_GENERAL															= AILOGIC_BASE_VALUE + 212,
	AI_GENERAL_DEFEND_PATCH_TASK						= AILOGIC_BASE_VALUE + 213,
	AI_GENERAL_HOLD_REINFORCEMENT_TASK			= AILOGIC_BASE_VALUE + 214,
	AI_OBSTACLE_STATIC_OBJECT								= AILOGIC_BASE_VALUE + 215,
	
	AI_GENERAL_ARTILLERY										= AILOGIC_BASE_VALUE + 216,
	AI_GENERAL_AIR_FORCE										= AILOGIC_BASE_VALUE + 217,
	
	AI_GENERAL_ARTILLERY_GO_TO_POSITION			= AILOGIC_BASE_VALUE + 218,
	AI_UNIT_INFO_FOR_GENERAL								= AILOGIC_BASE_VALUE + 219,
	AI_GENERAL_AIR_FORCE_LAUNCH_FIGHTERS    = AILOGIC_BASE_VALUE + 220,
	
	AI_ENTRENCHMENT_CREATION								= AILOGIC_BASE_VALUE + 221,
	AI_FENCE_CREATION												= AILOGIC_BASE_VALUE + 222,
	AI_TRANSPORT_CLEARMINE_STATE						= AILOGIC_BASE_VALUE + 223,
	AI_TRANSPORT_PLACEMINE_STATE						= AILOGIC_BASE_VALUE + 224,
	AI_TRANSPORT_PLACEANTITANK_STATE				= AILOGIC_BASE_VALUE + 225,
	AI_FORMATION_REPAIRBRIDGE_STATE					= AILOGIC_BASE_VALUE + 226,
	AI_PLANE_FLY_DEAD_STATE									= AILOGIC_BASE_VALUE + 227,
	AI_TRANSPORT_REPAIRBRIDGE_STATE					= AILOGIC_BASE_VALUE + 228,
	AI_ENEMYREMEMBERER											= AILOGIC_BASE_VALUE + 229,
	AI_TRANSPORT_BUILDBRIDGE_STATE					= AILOGIC_BASE_VALUE + 230,
	AI_BRIDGE_CREATION											= AILOGIC_BASE_VALUE + 231,
	AI_FORMATION_REPAIRBUILSING_STATE				= AILOGIC_BASE_VALUE + 232,
	AI_SPAN_LOCK														= AILOGIC_BASE_VALUE + 233,
	AI_GENERAL_INTEDANT											= AILOGIC_BASE_VALUE + 234,
	AI_GENERAL_TASK_DEFENDSTORAGE						= AILOGIC_BASE_VALUE + 235,
	AI_TRANSPORT_REPAIRBUILDING_STATE				= AILOGIC_BASE_VALUE + 236,
	AI_GENERAL_TASK_RECAPTURESTORAGE				= AILOGIC_BASE_VALUE + 237,
	AI_RESUPPLY_CELL_INFO										= AILOGIC_BASE_VALUE + 238,
	AI_WAIT_FOR_RECAPTURE_STORAGE						= AILOGIC_BASE_VALUE + 239,
	
	AI_MECH_UNIT_REST_STATE									=	AILOGIC_BASE_VALUE + 240,
	AI_GENERAL_TASK_RESUPPLYCELL						=	AILOGIC_BASE_VALUE + 241,
	
	AI_STANDART_SMOOTH_MECH_PATH						= AILOGIC_BASE_VALUE + 242,
	AI_STANDART_SMOOTH_SOLDIER_PATH					= AILOGIC_BASE_VALUE + 243,
	
	AI_FLAG																	=	AILOGIC_BASE_VALUE + 244,
	AI_PLANES_FORMATION											=	AILOGIC_BASE_VALUE + 245,
	AI_PLAN_IN_FORMATION_SMOOTHPATH					=	AILOGIC_BASE_VALUE + 246,
	AI_LINE_PATH_FRACTION										=	AILOGIC_BASE_VALUE + 247,
	AI_ARC_PATH_FRACTION										=	AILOGIC_BASE_VALUE + 248,
	AI_FORMATION_INSTALL_MORTAR_STATE				= AILOGIC_BASE_VALUE + 249,
	AI_TRANSPORT_MOVE_TO_RESUPPLYCELL_STATE	= AILOGIC_BASE_VALUE + 250,
	AI_GENERAL_TASK_SWARM_TO_POINT					= AILOGIC_BASE_VALUE + 251,
	AI_GENERAL_DELAYED_TASK_WAIT_FORREADY		= AILOGIC_BASE_VALUE + 252,
	
	AI_ANIM_UNIT_MECH												= AILOGIC_BASE_VALUE + 253,
	AI_ANIM_UNIT_SOLDIER										= AILOGIC_BASE_VALUE + 254,
	
	AI_SOLDIER_USE_STATE										= AILOGIC_BASE_VALUE + 255,
	AI_FORMATION_STATE_ENTER_TRANSPORT_CHEAT_PATH	= AILOGIC_BASE_VALUE + 256,
	
	AI_FORMATION_ENTER_BUILDING_NOW_STATE		= AILOGIC_BASE_VALUE + 257,
	AI_FORMATION_ENTER_ENTRENCHMENT_NOW_STATE	= AILOGIC_BASE_VALUE + 258,
	
	AI_MOVE_TO_GRID_STATE										= AILOGIC_BASE_VALUE + 259,
	AI_GENERAL_TASK_CHEKCDANGER							= AILOGIC_BASE_VALUE + 260,
};
#endif // __AI_CLASSES_ID_H__
