#ifndef __AI_CONSTS_H__
#define __AI_CONSTS_H__
#pragma ONCE
struct SAIConsts
{
	enum 
	{ 
		MAX_MAP_SIZE = 1024, 
		INFINITY_PATH_LIMIT = 5000, 
		MAX_LENGTH_OF_SMALL_PATH = 20, 
		MAX_NUMBER_OF_UNITS = 3000,
		AI_SEGMENT_DURATION = 50,
		TILE_SIZE = 32,
		MAX_NUM_OF_PLAYERS = 16,
		VIS_POWER = 7
	};
};
#endif // __AI_CONSTS_H__
