#ifndef __GENERAL_CONSTS_H__
#define __GENERAL_CONSTS_H__
#pragma ONCE
struct SGeneralConsts
{
	static int TIME_DONT_SEE_ENEMY_BEFORE_FORGET;
	
	static int SCOUT_FREE_POINT;
	static int SCOUT_POINTS;
	static NTimer::STime TIME_SONT_SEE_AA_BEFORE_FORGET;

	static int AVIATION_PERIOD_MAX;
	static int AVIATION_PERIOD_MIN;

	static int FIGHTER_PERIOD_MAX;
	static int FIGHTER_PERIOD_MIN;
	static float FIGHTER_INTERCEPT_OFFSET;

	static float AVATION_LONG_PERIOD_PROBABILITY;
	static float AVATION_PERIOD_MULTIPLY;
	static float PLAYER_FORCE_COEFFICIENT;
	
	static const int RESISTANCE_CELL_SIZE;
	static float TIME_TO_FORGET_ANTI_ARTILLERY;
	static float TIME_DONT_SEE_EMPTY_ARTILLERY_BEFORE_FORGET;
	static float TIME_TO_FORGET_UNIT;
	static float TIME_TO_ARTILLERY_FIRE;
	static float PROBABILITY_TO_SHOOT_AFTER_ARTILLERY_FIRE;
	static float SHOOTS_OF_ARTILLERY_FIRE;
	static float MIN_WEIGHT_TO_ARTILLERY_FIRE;
	static float MIN_WEIGHT_TO_SEND_BOMBERS;
	static float MIN_WEIGHT_TO_SEND_SWARM;
	static int SWARM_ADDITIONAL_ITERATIONS;
	static float SWARM_WEIGHT_COEFFICIENT;

	static int GENERAL_UPDATE_PERIOD;	

	static float REPAIR_STORAGE_PROBABILITY;
	static float RECAPTURE_STORAGE_PROBALITY;
	static float RECAPTURE_STORAGE_MAX_DISTANCE;
	static int RECAPTURE_ARTILLERY_TANKS_NUMBER;

	static int RESUPPLY_CELL_AFTER_TRANSPORT_DEATH;
	static int RESUPPLY_CELL_AFTER_TRANSPORT_DEATH_RAND;
	static float INTENDANT_DANGEROUS_CELL_RADIUS;
	
	static int TIME_TO_WAIT_SWARM_READY;
	static int TIME_TO_WAIT_SWARM_READY_RANDOM;

	static int TIME_SWARM_DURATION;
	static int TIME_SWARM_DURATION_RANDOM;
	static void Init();
};
#endif // __GENERAL_CONSTS_H__
