#define IDC_RMG_COS_ADD_FILTER_BUTTON   3
#define IDOK2                           3
#define IDC_RMG_COS_DELETE_OBJECT_SET_BUTTON 4
#define IDCANCEL2                       4
#define IDC_SO_DIPLOMACY_DELETE_BUTTON  4
#define IDC_RMG_COS_ADD_LAYER_BUTTON    5
#define IDC_RMG_COS_DELETE_LAYER_BUTTON 6
#define IDC_RMG_COS_ADD_OBJECT_BUTTON   7
#define IDC_RMG_COS_DELETE_OBJECT_BUTTON 8
#define IDD_ABOUTBOX                    100
#define IDR_LISTBAR                     101
#define IDD_MULTITREECONRTOL_DIALOG     102
#define IDC_TEMPLATE_TREE               103
#define IDR_MAINFRAME                   128
#define IDT_EDIT_BUTTONS                128
#define IDR_GUI_EDITOR                  129
#define IDR_EDITORTYPE                  129
#define IDR_ANIMATIONS_EDITOR           130
#define IDR_TEMPLATE_EDITOR             131
#define IDR_EFFECT_EDITOR               133
#define IDR_OBJECT_EDITOR               134
#define IDR_MESH_EDITOR                 135
#define IDR_BUILDING_EDITOR             137
#define IDR_FENCE_EDITOR                140
#define IDR_MINE_EDITOR                 144
#define IDR_BRIDGE_EDITOR               145
#define ID_TOOLS_CUSTOMIZE              200
#define IDS_COMMANDS                    201
#define IDR_CONTROL_TOOLBAR             250
#define IDC_MOVE_OBJECT_CURSOR          254
#define IDB_RADIOBUTTON                 255
#define IDB_BUTTON                      256
#define IDI_MOUSE                       261
#define IDR_BUTTON_MENU                 264
#define IDR_ADD_TEMPLATE_MENU           264
#define IDR_ALIGN_MENU                  265
#define IDD_SELECT_TEXTURE              266
#define IDB_DIALOG                      267
#define IDD_BUTTON_PROPERTIES           270
#define IDB_STATIC                      271
#define IDD_STATIC_PROPERTIES           272
#define IDD_SIMPLE_PROPERTIES           274
#define IDB_SLIDER                      276
#define IDD_SLIDER_PROPERTIES           277
#define IDB_SCROLL_BAR                  278
#define IDB_LIST_CONTROL                279
#define IDD_LIST_PROPERTIES             280
#define IDR_TEMPLATE_MENU               281
#define IDB_EDIT_LINE                   282
#define IDD_DIALOG2                     284
#define IDB_TREEBMP                     288
#define IDD_DIALOG3                     294
#define IDD_REFERENCE_DIALOG            294
#define IDB_CHECK_BMP                   295
#define IDR_MAPEDITORTOOLBAR            298
#define IDT_TOOLS_BUTTONS               298
#define IDD_DIALOGFILLAREA              300
#define IDR_INSERT_TREE_ITEM_MENU       302
#define IDR_INTERPOLATE_TREE_ITEM_MENU  303
#define IDD_DIALOG4                     304
#define IDD_DIALOG1                     305
#define IDR_OBJECTTOOLBAR               308
#define IDD_DIALOG5                     310
#define IDD_TAB_SIMPLE_OBJECTS          310
#define IDD_DIALOGNEWMAP                312
#define IDD_NEW_MAP                     312
#define IDD_SET_DIRECTORIES_DIALOG      313
#define IDD_DIALOG6                     314
#define IDD_DIALOGSHADE                 315
#define IDD_TAB_TERRAIN_ALTITUDES       315
#define IDD_DIALOGFILTEREDITOR          316
#define IDD_DIALOG7                     317
#define IDD_DIALOG8                     318
#define IDD_TAB_SIMPLE_OBJECTS_SET_FILTER 318
#define IDD_RUN_BATCH_MODE_DIALOG       319
#define IDB_PUSHPIN                     321
#define IDD_DIALOG9                     323
#define IDD_DIALOGPROPERTIE2            324
#define IDD_PROPERTY                    324
#define IDR_KEYFRAME_ZOOM_MENU          325
#define IDD_DIALOGTOOLS                 326
#define IDD_TAB_TOOLS                   326
#define IDD_DIALOG10                    327
#define IDD_GROUPMANAGER                329
#define IDD_TAB_GROUPS                  329
#define IDD_DIALOG11                    331
#define IDD_TAB_GROUPS_GET_GROUP_ID     331
#define IDC_ADD                         336
#define IDC_CURSOR1                     337
#define IDD_PROGRESS_DIALOG             338
#define IDD_DIALOG12                    339
#define IDD_DIALOGINSERTBYGROUPID       340
#define IDD_TAB_GROUPS_GET_SCRIPT_ID    340
#define IDD_DIALOGFENCESETUP            341
#define IDD_TAB_VO_FENCES               341
#define IDD_DIALOGTREHCHSETUP           342
#define IDD_TAB_VO_ENTRENCHMENTS        342
#define IDB_EDITOR_STARTUP              344
#define IDD_DIALOG13                    345
#define IDD_DIALOGOPTIONS               348
#define IDD_SCRIPT_NAME                 348
#define IDD_DIALOG14                    349
#define IDD_DIALOGENTERAREAMAP          350
#define IDD_TAB_TOOLS_AREAD_NAME        350
#define IDD_RIVERSETUP                  351
#define IDD_ADVANCEDIALOG               353
#define IDD_BRIDGESETUP                 354
#define IDD_TAB_VO_BRIDGES              354
#define IDD_OPTION                      355
#define IDD_OPTIONS                     355
#define IDD_MAP_EDITOR_OPTIONS          355
#define IDD_PASTENAME                   356
#define IDD_MINIMAPDIALOG               357
#define IDD_MINIMAP                     357
#define IDD_DIALOG_CREATE_FOREST        359
#define IDD_COMPOSER_OBJECT_SET         359
#define IDD_RMG_CREATE_OBJECT_SET       359
#define IDD_FOREST_SETUP                362
#define IDD_DIALOG_WOOD_PROPERTIES      363
#define IDD_RMG_CF_OS_OBJECT_PROPERTIES 363
#define IDD_RANDOM_MAP_GENERATOR        364
#define IDD_TAB_RANDOM_MAP_GENERATOR    364
#define IDC_DIALOG_CREATE_CONTAINER     365
#define IDD_RMG_CREATE_CONTAINER        365
#define IDD_DIALOG_PATCH_PROPERTIES     366
#define IDD_RMG_PATCH_PROPERTIES        366
#define IDD_RMG_TEMPALETE_EDITOR        367
#define IDD_RMG_CREATE_GRAPH            367
#define IDD_AI_START_COMMAND_PROPERTIES 368
#define IDD_TAB_VO_VECTOR_STRIPE_OBJECTS 370
#define IDD_TAB_VO_FORESTS              371
#define IDD_TAB_SOUNDS                  372
#define IDD_UNIT_CREATION_TEMP_RU_STORAGE_EDITOR 373
#define IDD_PE_SELECT_STRINGS           373
#define IDD_RMG_CREATE_TILE_SET         374
#define IDM_RMG_COMPOSERS_POPUP_MENUS   374
#define IDD_RMG_GRAPH_NODE_PROPERTIES   375
#define IDD_RMG_GRAPH_LINK_PROPERTIES   376
#define IDM_RMG_CREATE_GRAPH            376
#define IDD_RMG_CREATE_TEMPLATE         377
#define IDM_RMG_CREATE_CONTAINER        377
#define IDM_RMG_CREATE_TEMPLATE         378
#define IDD_RMG_TEMPLATE_GRAPH_PROPERTIES 378
#define IDD_RMG_TEMPLATE_VSO_PROPERTIES 379
#define IDM_PE_POPUP_MENUS              379
#define IDD_RMG_TEMPLATE_FIELD_PROPERTIES 380
#define IDM_TAB_POPUP_MENUS             380
#define IDD_PE_POINTS_LIST              381
#define IDM_CF_POPUP_MENUS              381
#define IDD_PE_POINT_PROPERTIES         382
#define IDM_RMG_CREATE_FIELD            382
#define IDD_TAB_TILE_EDIT               383
#define IDD_TAB_AI_GENERAL              384
#define IDD_TAB_AI_GENERAL_ENTER_SCRIPT_ID 385
#define IDD_TAB_AI_GENERAL_SET_POSITION_TYPE 386
#define IDD_TAB_SIMPLE_OBJECTS_DIPLOMACY 387
#define IDD_PLAYERS_CAMERA_ANCHORS      388
#define IDB_DEFAULT_OBJECT_IMAGE        388
#define IDD_CREATE_FILTER               389
#define IDI_RMG_CREATE_FIELD_TILES      389
#define IDI_RMG_CF_TERRAIN_TAB          389
#define IDD_CREATE_FILTER_NAME          390
#define IDI_RMG_CREATE_FIELD_OBJECTS    390
#define IDI_RMG_CF_OBJECTS_TAB          390
#define IDI_RMG_CREATE_FIELD_HEIGHTS    391
#define IDI_RMG_CF_HEIGHTS_TAB          391
#define IDI_FENCES_TAB                  392
#define IDI_ENTRENCHMENTS_TAB           393
#define IDI_ROADS_TAB                   394
#define IDB_ENTRENCHMENT_ICON           394
#define IDI_RIVERS_TAB                  395
#define IDI_BRIDGES_TAB                 396
#define IDI_TERRAIN_TAB                 397
#define IDI_HEIGHTS_TAB                 398
#define IDI_FIELDS_TAB                  399
#define IDI_OBJECTS_TAB                 400
#define IDD_ABOUT                       1000
#define IDD_PROGRESS                    1001
#define IDD_CREATE_RANDOM_MAP           1003
#define IDD_OPEN_MAP                    1004
#define IDD_RMG_CREATE_FIELD            1005
#define IDC_SLIDER1                     1006
#define IDD_RMG_CF_TERRAIN_SHELLS       1006
#define IDC_CF_H_POSITIVE_RATIO_SLIDER  1006
#define IDD_RMG_CF_OBJECTS_SHELLS       1009
#define IDD_RMG_CF_HEIGHTS              1010
#define IDC_LEFT                        1011
#define IDD_TAB_TERRAIN_FIELDS          1011
#define IDC_RIGHT                       1012
#define IDD_RMG_CF_TS_TILE_PROPERTIES   1012
#define IDC_TOP                         1013
#define IDD_RMG_CF_TS_PROPERTIES        1013
#define IDC_BOTTOM                      1014
#define IDD_RMG_CF_OS_PROPERTIES        1014
#define IDC_LEFT2                       1015
#define IDC_WINDOW_NAME                 1015
#define IDC_PROGRESS_BAR                1017
#define IDC_PROGRESS_LABEL              1018
#define IDC_LEFTMAP                     1023
#define IDC_TOPMAP                      1024
#define IDC_RIGHTMAP                    1025
#define IDC_BOTTOMMAP                   1026
#define IDC_HLEFTMAP                    1027
#define IDC_MAX                         1027
#define IDC_CRM_TEMPLATE_LABEL          1027
#define IDC_HTOPMAP                     1028
#define IDC_MIN                         1028
#define IDC_CRM_TEMPLATE_EDIT           1028
#define IDC_HRIGHTMAP                   1029
#define IDC_CRM_TEMPLATE_BROWSE_BUTTON  1029
#define IDC_HBOTTOMMAP                  1030
#define IDC_STEP                        1030
#define IDC_CRM_CONTEXT_LABEL           1030
#define IDC_WIDTH                       1031
#define IDC_CRM_CONTEXT_EDIT            1031
#define IDC_HEIGHT                      1032
#define IDC_CRM_CONTEXT_BROWSE_BUTTON   1032
#define IDC_SELLEFTMAP                  1033
#define IDC_CRM_MAP_LABEL               1033
#define IDC_SELTOPMAP                   1034
#define IDC_CRM_MAP_EDIT                1034
#define IDC_SLEFTMAP                    1035
#define IDC_SELRIGHTMAP                 1035
#define IDC_CRM_MAP_BROWSE_BUTTON       1035
#define IDC_STOPMAP                     1036
#define IDC_SELBOTTOMMAP                1036
#define IDC_CRM_GRAPH_LABEL             1036
#define IDC_SRIGHTMAP                   1037
#define IDC_POSITION                    1037
#define IDC_CRM_GRAPH_EDIT              1037
#define IDC_SBOTTOMMAP                  1038
#define IDC_CRM_SETTING_LABEL           1038
#define IDC_CHECK_ICON                  1039
#define IDC_CHECK_TEXT                  1040
#define IDC_CAPTION_TEXT                1041
#define IDC_LEFT_RADIO                  1042
#define IDC_HCENTER_RADIO               1043
#define IDC_RIGHT_RADIO                 1044
#define IDC_TOP_RADIO                   1045
#define IDC_COLOR_BUTTON                1045
#define IDC_VCENTER_RADIO               1046
#define IDC_SPECULAR_BUTTON             1046
#define IDC_BOTTOM_RADIO                1047
#define IDC_TEXT_COLOR_BUTTON           1048
#define IDC_CHECK_VERTICAL              1055
#define IDC_TEXTURE_TREE                1067
#define IDC_ICON_RADIO                  1068
#define IDC_TEXT_RADIO                  1069
#define IDC_COLUMN_LIST                 1069
#define IDC_ICONTEXT_RADIO              1070
#define IDC_SPACE_LEFT                  1071
#define IDC_SPACE_TOP                   1072
#define IDC_COLUMN_WIDTH                1073
#define IDC_VERTICAL_SPACE              1074
#define IDC_HORIZONTAL_SPACE            1075
#define IDC_ITEM_HEIGHT                 1076
#define IDC_WINDOWTYPE_COMBO            1077
#define IDC_EDIT_TEMPLATE_BUTTON        1078
#define IDC_SCROLLBAR_WIDTH             1079
#define IDC_COLUMNS_NUMBER              1080
#define IDC_LEFT_SCROLLBAR_CHECK        1081
#define IDC_SCROLLBAR_ALWAYS_CHECK      1082
#define IDC_EDITLEFT                    1083
#define IDC_EDITBOTTOM                  1086
#define IDC_EDITTOP                     1087
#define IDC_EDITRIGHT                   1088
#define IDC_BUTTON1                     1089
#define IDC_REAL_MINIMAP_UPDATE         1089
#define IDC_MINIMAP_GAME                1089
#define IDC_CF_H_PROFILE_BROWSE_BUTTON  1089
#define IDC_FIELD_BROWSE                1089
#define IDC_BUTTON4                     1090
#define IDC_BUTTON5                     1091
#define IDC_REFERENCE_LIST              1092
#define IDC_RADIO1                      1094
#define IDC_ROAD                        1094
#define IDC_RADIO4                      1094
#define IDC_SHADE_TYPE0                 1094
#define IDC_VSO_SINGLE_WIDTH_RADIO      1094
#define IDC_RMG_GLP_LINK_TYPE_00_RADIO_BUTTON 1094
#define IDC_TOOLS_SCRIPT_AREA_RADIO_BUTTON 1094
#define IDC_AIG_SIDE_0_RADIO_BUTTON     1094
#define IDC_TAB_AI_GENERAL_SPT_TYPE0    1094
#define IDC_SO_DIPLOMACY_SIDE0_BUTTON   1094
#define IDC_OPTIONS_DEF_EXTENTION_BZM   1094
#define IDC_RMG_GLP_LINK_TYPE_01_RADIO_BUTTON 1095
#define IDC_OPTIONS_DEF_EXTENTION_XML   1095
#define IDC_COMBO1                      1095
#define IDC_SHADE_TYPE1                 1095
#define IDC_VSO_MUlTI_WIDTH_RADIO       1095
#define IDC_AIG_SIDE_1_RADIO_BUTTON     1095
#define IDC_TAB_AI_GENERAL_SPT_TYPE1    1095
#define IDC_SO_DIPLOMACY_SIDE1_BUTTON   1095
#define IDC_NEW_MAP_SIZE_COMBO_BOX      1095
#define IDC_NEW_MAP_SIZE_X_COMBO_BOX    1095
#define IDC_CF_TS_SEASON_COMBO          1095
#define IDC_FIELD_FIELD_COMBO           1095
#define IDC_TOOLS_SA_RECT_RADIO_BUTTON  1096
#define IDC_RADIO2                      1096
#define IDC_FENCE                       1096
#define IDC_RADIO5                      1096
#define IDC_SHADE_TYPE2                 1096
#define IDC_VSO_ALL_WIDTH_RATIO         1096
#define IDC_NEW_MAP_SEASON_COMBO_BOX    1096
#define IDC_SHADE_TYPE3                 1097
#define IDC_NEW_MAP_SIZE_Y_COMBO_BOX    1097
#define IDC_SHADE_TYPE4                 1098
#define IDC_NEW_MAP_MOD_COMBO_BOX       1098
#define IDC_LIST2                       1100
#define IDC_COMBO2                      1101
#define IDC_RMG_CG_GRAPHS_LIST          1101
#define IDC_ABOUT_VERSION               1101
#define IDC_LIST1                       1102
#define IDC_RMG_CT_FORESTS_CIRCLE_SOUND_COMBO 1102
#define IDC_ABOUT_PROGRAM_TITLE         1102
#define IDC_SO_SET_FILTER_LIST          1102
#define IDC_LIST3                       1103
#define IDC_VO_FENCES_LIST              1103
#define IDC_CF_TS_TILES_LIST            1103
#define IDC_CHECK2                      1104
#define IDC_SO_FILTER_SHORTCUT_09       1104
#define IDC_CF_TS_AVAILABLE_TILES_LIST  1104
#define IDC_FIELD_CHECK_PASSABILITY_CHECK_BOX 1104
#define IDC_CHECK3                      1105
#define IDC_CF_TS_SHELLS_LIST           1105
#define IDC_FIELD_RANDOMIZE_POLYGON_CHECK_BOX 1105
#define IDC_CHECK4                      1106
#define IDC_SO_FILTER_SHORTCUT_01       1106
#define IDC_CHECK5                      1107
#define IDC_SO_FILTER_SHORTCUT_05       1107
#define IDC_CHECK6                      1108
#define IDC_SO_FILTER_SHORTCUT_02       1108
#define IDC_CHECK7                      1109
#define IDC_SO_FILTER_SHORTCUT_04       1109
#define IDC_CHECK8                      1110
#define IDC_SO_FILTER_SHORTCUT_00       1110
#define IDC_CHECK9                      1111
#define IDC_SO_FILTER_SHORTCUT_03       1111
#define IDC_CHECK1                      1112
#define IDC_FORCE_MODE_CHECK            1112
#define IDC_SO_FILTER_SHORTCUT_4        1112
#define IDC_SO_FILTER_SHORTCUT_06       1112
#define IDC_FIELD_REMOVE_OBJECTS_CHECK_BOX 1112
#define IDC_CHECK10                     1113
#define IDC_SO_FILTER_SHORTCUT_07       1113
#define IDC_FIELD_FILL_TERRAIN_CHECK_BOX 1113
#define IDC_CHECK11                     1114
#define IDC_SO_FILTER_SHORTCUT_08       1114
#define IDC_FIELD_FILL_OBJECTS_CHECK_BOX 1114
#define IDC_FIELD_FILL_HEIGHTS_CHECK_BOX 1115
#define IDC_FIELD_UPDATE_MAP_CHECK_BOX  1116
#define IDC_STATIC2                     1117
#define IDC_EDIT1                       1118
#define IDC_EDIT2                       1119
#define IDC_EDIT3                       1120
#define IDC_BROWSE_SOURCE_DIR           1121
#define IDC_EDIT26                      1121
#define IDC_CF_H_SIZE_MAX_EDIT          1121
#define IDC_BROWSE_DEST_DIR             1122
#define IDC_EDIT27                      1122
#define IDC_CF_H_POSITIVE_RATIO_EDIT    1122
#define IDC_EDIT_SOURCE_DIR             1123
#define IDC_EDIT28                      1123
#define IDC_EDIT_DEST_DIR               1124
#define IDC_EDIT29                      1124
#define IDC_BUTTON2                     1125
#define IDC_EDIT_SEARCH_MASK            1125
#define IDC_PIN_BUTTON                  1125
#define IDC_TREE1                       1126
#define IDC_RMG_CG_ADD_GRAPH_BUTTON     1127
#define IDC_RADIO3                      1128
#define IDC_RMG_CG_DELETE_GRAPH_BUTTON  1128
#define IDC_TOOLS_DAMAGE_RADIO_BUTTON   1128
#define IDC_SPIN1                       1129
#define IDC_TOOLS_DAMAGE_SPIN           1129
#define IDC_BATCH_MODE_PROGRESS         1132
#define IDC_PROGRESS_DIALOG_STATIC      1133
#define IDC_SLIDER2                     1134
#define IDC_SLIDER3                     1135
#define IDC_RADIO6                      1135
#define IDC_TOOLS_SA_CIRCLE_RADIO_BUTTON 1135
#define IDC_SLIDER4                     1136
#define IDC_STATIC100                   1136
#define IDC_SLIDER5                     1137
#define IDC_STATIC101                   1137
#define IDC_SLIDER6                     1138
#define IDC_STATIC102                   1138
#define IDC_SLIDER7                     1139
#define IDC_STATIC103                   1139
#define IDC_SLIDER8                     1140
#define IDC_STATIC104                   1140
#define IDC_SLIDER9                     1141
#define IDC_STATIC105                   1141
#define IDC_STATIC106                   1142
#define IDC_STATIC107                   1143
#define IDC_BUTTONADDPASTEGROUP         1144
#define IDC_EDIT4                       1145
#define IDC_MINIMAP_VIEW                1145
#define IDC_RMG_GLP_LINK_LINE_LENGTH_EDIT 1145
#define IDC_MINIMAP_CLOSE               1146
#define IDC_MINIMAP_PARTY               1147
#define IDC_EDIT5                       1147
#define IDC_RMG_GLP_LINK_LINE_WIDTH_EDIT 1147
#define IDC_MINIMAP_LAYER_0             1148
#define IDC_EDIT7                       1148
#define IDC_MINIMAP_LAYER_1             1149
#define IDC_EDIT8                       1149
#define IDC_MINIMAP_LAYER_2             1150
#define IDC_EDIT9                       1150
#define IDC_MINIMAP_LAYER_3             1151
#define IDC_EDIT6                       1151
#define IDC_RMG_GLP_LINK_LINE_DISTURBANCE_EDIT 1151
#define IDC_MINIMAP_LAYER_4             1152
#define IDC_EDIT10                      1152
#define IDC_MINIMAP_LAYER_5             1153
#define IDC_EDIT12                      1153
#define IDC_MINIMAP_PARTY_LABEL         1154
#define IDC_EDIT13                      1154
#define IDC_MINIMAP_EDITOR              1155
#define IDC_EDIT14                      1155
#define IDC_EDIT11                      1156
#define IDC_MINIMAP_PROPORTIONAL        1156
#define IDC_EDIT15                      1157
#define IDC_FOREST_EDGE_LABEL           1157
#define IDC_OSC_LAYERS_LABEL            1157
#define IDC_EDIT17                      1158
#define IDC_FOREST_HEART_LABEL          1158
#define IDC_OSC_OBJECTS_LABEL           1158
#define IDC_EDIT18                      1159
#define IDC_FOREST_WOODS_LABEL          1159
#define IDC_OSC_AVAILIABLE_OBJECTS_LABEL 1159
#define IDC_EDIT19                      1160
#define IDC_FOREST_EDGE_LIST            1160
#define IDC_OSC_LAYERS_LIST             1160
#define IDC_EDIT16                      1161
#define IDC_FOREST_HEART_LIST           1161
#define IDC_OSC_OBJECTS_LIST            1161
#define IDC_EDIT20                      1162
#define IDC_FOREST_WOODS_LIST           1162
#define IDC_OSC_AVAILIABLE_OBJECTS_LIST 1162
#define IDC_EDIT22                      1163
#define IDC_FOREST_EDGE_ADD_BUTTON      1163
#define IDC_EDIT23                      1164
#define IDC_FOREST_EDGE_REMOVE_BUTTON   1164
#define IDC_EDIT24                      1165
#define IDC_FOREST_HEART_ADD_BUTTON     1165
#define IDC_EDIT21                      1166
#define IDC_FOREST_HEART_REMOVE_BUTTON  1166
#define IDC_EDIT25                      1167
#define IDC_FOREST_NAME_LABEL           1167
#define IDC_OSC_NAME_LABEL              1167
#define IDC_BUTTON3                     1168
#define IDC_GROUPS_ADD_PROPERTY_BUTTON  1168
#define IDC_AIG_DELETE_POSITIONS_BUTTON 1168
#define IDC_NEW_MAP_NAME_BROWSE_BUTTON  1168
#define IDC_FOREST_NAME_EDIT            1169
#define IDC_OSC_NAME_EDIT               1169
#define IDC_FOREST_WOOD_PROPERTIES_ICON 1170
#define IDC_RMG_CF_OS_OP_ICON           1170
#define IDC_FOREST_WOOD_PROPERTIES_NAME 1171
#define IDC_RMG_CF_OS_OP_NAME_LABEL_RIGHT 1171
#define IDC_FOREST_WOOD_PROPERTIES_PATH 1172
#define IDC_RMG_CF_OS_OP_PATH_LABEL_RIGHT 1172
#define IDC_FOREST_WOOD_PROPERTIES_WEIGHT 1173
#define IDC_RMG_CF_OS_OP_WEIGHT_EDIT    1173
#define IDC_FOREST_WOOD_PROPERTIES_VIS_TYPE 1174
#define IDC_FOREST_DELETE_BUTTON        1174
#define IDC_OSC_DELETE_BUTTON           1174
#define IDC_RMG_CF_OS_OP_VIS_TYPE_LABEL_RIGHT 1174
#define IDC_FOREST_WOOD_PROPERTIES_GAME_TYPE 1175
#define IDC_FOREST_SETUP_CURRENT        1175
#define IDC_FORESTS_FOREST              1175
#define IDC_OSC_DELETE_BUTTON2          1175
#define IDC_RMG_CF_OS_OP_GAME_TYPE_LABEL_RIGHT 1175
#define IDC_FOREST_SETUP_RATIO          1176
#define IDC_FORESTS_RATIO               1176
#define IDC_FOREST_SETUP_RATIO_LABEL    1177
#define IDC_FORESTS_RATIO_LABEL_RIGHT   1177
#define IDC_FOREST_SETUP_EDGE           1178
#define IDC_FORESTS_EDGE                1178
#define IDC_FOREST_SETUP_EDGE_LABEL     1179
#define IDC_FORESTS_EDGE_LABEL_RIGHT    1179
#define IDC_FOREST_SETUP_SECTION        1180
#define IDC_FORESTS_SECTION_DELIMITER_00 1180
#define IDC_FOREST_SETUP_ADDED_EDGE     1181
#define IDC_FORESTS_ADDED_EDGE          1181
#define IDC_FOREST_SETUP_ADDED_HEART    1182
#define IDC_RMG_BUTTON_CREATE           1182
#define IDC_FORESTS_ADDED_HEART         1182
#define IDC_FOREST_SETUP_ADDED_ALL      1183
#define IDC_RMGENERATOR_PATCHES_LIST    1183
#define IDC_FORESTS_ADDED_ALL           1183
#define IDC_FOREST_SETUP_RADUIS         1184
#define IDC_FORESTS_RADIUS              1184
#define IDC_FOREST_SETUP_RADUIS_LABEL   1185
#define IDC_FORESTS_RADIUS_LABEL_RIGHT  1185
#define IDC_RMGENERATOR_CONTAINER_LIST  1186
#define IDC_RMG_CC_PATCHES_LIST         1186
#define IDC_RMGENERATOR_PATCHES_LABEL   1187
#define IDC_RMGENERATOR_CONTAINERS_LABEL 1188
#define IDC_RMG_CC_CONTAINERS_LABEL     1188
#define IDC_RMGENERATOR_CONTAINERS_COMBO_BOX 1189
#define IDC_RMGENERATOR_ADD_BUTTON      1190
#define IDC_RMGENERATOR_REMOVE_BUTTON   1191
#define IDC_RMGENERATOR_DELETE_BUTTON   1192
#define IDC_PATCH_PROPERTIES_NAME       1193
#define IDC_PATCH_PROPERTIES_PATH       1194
#define IDC_RMG_PP_PATH_LABEL_RIGHT     1194
#define IDC_PATCH_PROPERTIES_SIZE       1195
#define IDC_RMG_PP_SIZE_LABEL_RIGHT     1195
#define IDC_PATCH_PROPERTIES_CHECK_BOX_00 1196
#define IDC_RMG_PP_CHECKBOX_0           1196
#define IDC_PATCH_PROPERTIES_CHECK_BOX_01 1197
#define IDC_RMG_PP_CHECKBOX_90          1197
#define IDC_PATCH_PROPERTIES_CHECK_BOX_02 1198
#define IDC_RMG_PP_CHECKBOX_180         1198
#define IDC_PATCH_PROPERTIES_CHECK_BOX_03 1199
#define IDC_RMG_PP_CHECKBOX_270         1199
#define IDC_PATCH_PROPERTIES_ICON       1200
#define IDC_RMG_SELECTION_LABEL         1201
#define IDC_SCP_COMMANDS_LIST           1229
#define IDC_SCP_PROPERTIES_BUTTON       1230
#define IDC_SCP_DELETE_BUTTON           1231
#define IDC_SCP_EDIT_BUTTON             1232
#define IDC_SCP_ADD_BUTTON              1233
#define IDC_SHADE_MIN_BRUSH_LABEL       1234
#define IDC_SHADE_BRUSH_SIZE_LABEL_LEFT 1234
#define IDC_SHADE_MAX_BRUSH_LABEL       1235
#define IDC_SHADE_BRUSH_SIZE_LABEL_RIGHT 1235
#define IDC_SHADE_BRUSH_SIZE            1236
#define IDC_BRUSH_SIZE_LABEL            1238
#define IDC_SHADE_BRUSH_SIZE_LABEL_BOTTOM 1238
#define IDC_LEVEL_LABEL                 1239
#define IDC_SHADE_LEVEL_LABEL_BOTTOM    1239
#define IDC_SHADE_HEIGHT_LABEL          1240
#define IDC_SHADE_HEIGHT_LABEL_LEFT     1240
#define IDC_SHADE_LEVELRATIO_LABEL      1241
#define IDC_SHADE_LEVEL_RATIO_LABEL_LEFT 1241
#define IDC_SHADE_HEIGHT                1242
#define IDC_SHADE_LEVELRATIO            1243
#define IDC_SHADE_LEVEL_RATIO           1243
#define IDC_SHADE_MAX_LABEL             1244
#define IDC_SHADE_MAX_LABEL_LEFT        1244
#define IDC_SHADE_GENERATE_BUTTON       1245
#define IDC_SHADE_ZERO_BUTTON           1246
#define IDC_SHADE_MAX                   1247
#define IDC_SHADE_MIN                   1248
#define IDC_SHADE_GRANULARITY_LABEL     1249
#define IDC_SHADE_GRANULARITY           1250
#define IDC_SHADE_LEVEL_TO_0            1251
#define IDC_SHADE_LEVEL_TO_1            1252
#define IDC_SHADE_LEVEL_TO_2            1253
#define IDC_SHADE_LEVEL_TO_3            1254
#define IDC_SHADE_LEVEL_LABEL           1255
#define IDC_SHADE_UPDATE_BUTTON         1256
#define IDC_SHADE_HEIGHT_LABEL_2        1258
#define IDC_SHADE_HEIGHT_LABEL_RIGHT    1258
#define IDC_SHADE_LEVELRATIO_LABEL_2    1259
#define IDC_FORESTS_FOREST_LABEL_LEFT   1259
#define IDC_SHADE_LEVEL_RATIO_LABEL_RIGHT 1259
#define IDC_SHADE_MAX_LABEL_2           1260
#define IDC_FORESTS_RATIO_LABEL_LEFT    1260
#define IDC_SHADE_MAX_LABEL_RIGHT       1260
#define IDC_SHADE_MIN_LABEL_2           1261
#define IDC_FORESTS_EDGE_LABEL_LEFT     1261
#define IDC_SHADE_MIN_LABEL_RIGHT       1261
#define IDC_FORESTS_RADIUS_LABEL_LEFT   1262
#define IDC_FORESTS_ADDED_LABEL_LEFT    1263
#define IDC_VSO_WIDTH_LABEL_LEFT        1264
#define IDC_VSO_SECTION_DELIMITER_00    1265
#define IDC_VSO_SECTION_DELIMITER_1     1266
#define IDC_VSO_OPACITY_LABEL_LEFT      1267
#define IDC_VSO_OPACITY                 1269
#define IDC_VSO_OPACITY_LABEL_RIGHT     1271
#define IDC_VSO_WIDTH_LABEL_RIGHT       1272
#define IDC_VSO_OBJECTS_LIST            1273
#define IDC_VSO_OBJECTS_LIST_LABEL      1274
#define IDC_VSO_WIDTH                   1275
#define IDC_SOUNDS_LABEL_LEFT           1276
#define IDC_UC_TEMP_RU_STORAGES_LIST    1279
#define IDC_SS_STRINGS_LIST             1279
#define IDC_OSC_FILTER_NAME_LABEL       1280
#define IDC_OSC_ADD_FILTER_BUTTON       1281
#define IDC_OSC_FILTER_NAME_COMBO       1282
#define IDC_OSC_ADD_FILTER_BUTTON2      1283
#define IDC_OSC_DELIMITER_00            1285
#define IDC_SOUNDS_SHOW_00              1287
#define IDC_SOUNDS_NAME                 1288
#define IDC_SOUNDS_DELIMITER_00         1289
#define IDC_SOUNDS_SHOW_01              1290
#define IDC_SOUNDS_SHOW_02              1291
#define IDC_SOUNDS_DELIMITER_01         1292
#define IDC_SOUNDS_AMBIENT_LABEL_LEFT   1293
#define IDC_SOUNDS_CIRCLE_LABEL_LEFT    1294
#define IDC_SOUNDS_AMBIENT_COMBO        1295
#define IDC_SOUNDS_CIRCLE_COMBO         1296
#define IDC_SOUNDS_FORESTS_LABEL_LEFT   1297
#define IDC_RMG_CC_PATCHES_LABEL        1298
#define IDC_RMG_CC_DELETE_BUTTON        1299
#define IDC_RMG_CC_ADD_BUTTON           1300
#define IDC_RMG_PP_PATH_LABEL_LEFT      1301
#define IDC_RMG_CC_ADD_CONTAINER_BUTTON 1301
#define IDC_RMG_PP_SIZE_LABEL_LEFT      1302
#define IDC_RMG_CC_DELETE_CONTAINER_BUTTON 1302
#define IDC_RMG_CT_ADD_GRAPH_BUTTON     1303
#define IDC_RMG_PP_PLACE_LABEL_LEFT     1303
#define IDC_RMG_CT_DELETE_GRAPH_BUTTON  1304
#define IDC_RMG_CT_ADD_FIELD_BUTTON     1305
#define IDC_RMG_CT_DELETE_FIELD_BUTTON  1306
#define IDC_RMG_COS_FILTER_NAME_LABEL   1307
#define IDC_RMG_CT_ADD_VSO_BUTTON       1307
#define IDC_RMG_COS_FILTER_NAME_COMBOBOX 1308
#define IDC_RMG_CT_DELETE_VSO_BUTTON    1308
#define IDC_RMG_COS_DELIMITER_00        1309
#define IDC_RMG_COS_OBJECT_SET_NAME_LABEL 1310
#define IDC_RMG_COS_OBJECT_SET_NAME_CONBOBOX 1311
#define IDC_RMG_COS_AVAILIABLE_OBJECTS_LABEL 1312
#define IDC_RMG_COS_AVAILIABLE_OBJECTS_LIST 1313
#define IDC_RMG_COS_LAYERS_LIST         1314
#define IDC_RMG_COS_LAYERS_LABEL        1315
#define IDC_RMG_COS_OBJECTS_LIST        1316
#define IDC_RMG_COS_OBJECTS_LABEL       1317
#define IDC_RMG_CC_CONTAINERS_LIST      1319
#define IDC_RMG_CC_PROPERTIES_BUTTON    1320
#define IDC_RMG_CC_CONTAINER_PROPERTIES_BUTTON 1321
#define IDC_RMG_CG_GRAPHS_LABEL         1321
#define IDC_RMG_CG_NODES_LABEL_TOP      1322
#define IDC_RMG_CT_GRAPH_PROPERTIES_BUTTON 1322
#define IDC_RMG_CG_NODES_PLACE          1323
#define IDC_RMG_CT_FIELD_PROPERTIES_BUTTON 1323
#define IDC_RMG_CG_GRAPH_PROPERTIES_BUTTON 1324
#define IDC_RMG_CT_VSO_PROPERTIES_BUTTON 1324
#define IDC_RMG_CG_NODES_SLIDER         1325
#define IDC_RMG_CG_NODES_SLIDER_LABEL_TOP 1326
#define IDC_RMG_CG_NODES_SLIDER_LABEL_BOTTOM 1327
#define IDC_RMG_CC_SAVE_BUTTON          1328
#define IDC_RMG_CG_CHECK_GRAPHS_BUTTON  1328
#define IDC_RMG_CG_SAVE_BUTTON          1329
#define IDC_RMG_GLP_LINKS_LABEL         1330
#define IDC_RMG_GLP_LINKS_LIST          1331
#define IDC_RMG_GLP_DELETE_LINK_BUTTON  1332
#define IDC_RMG_GLP_LINK_TYPE_LABEL     1333
#define IDC_RMG_GLP_LINK_DESK_LABEL     1334
#define IDC_RMG_GLP_LINK_DESC_EDIT      1335
#define IDC_RMG_GLP_LINK_DESC_BROWSE_BUTTON 1336
#define IDC_RMG_GLP_LINK_CORNER_LABEL   1337
#define IDC_RMG_GLP_LINK_CORNER_RADIUS_LABEL 1338
#define IDC_RMG_GLP_LINK_CORNER_RADIUS_EDIT 1339
#define IDC_RMG_GLP_LINK_CORNER_PARTS_LABEL 1340
#define IDC_RMG_GLP_LINK_CORNER_PARTS_EDIT 1341
#define IDC_RMG_GLP_LINK_LINE_LABEL     1342
#define IDC_RMG_GLP_LINK_LINE_LENGTH_LABEL 1343
#define IDC_RMG_GLP_LINK_LINE_WIDTH_LABEL 1344
#define IDC_RMG_GLP_LINK_LINE_DISTURBANCE_LABEL 1345
#define IDC_RMG_GNP_SIZE_LABEL_LEFT     1346
#define IDC_RMG_GNP_SIZE_LABEL_RIGHT    1347
#define IDC_RMG_GNP_CONTAINER_LABEL     1348
#define IDC_RMG_GNP_CONTAINER_EDIT      1349
#define IDC_RMG_GNP_CONTAINER_BROWSE_BUTTON 1350
#define IDC_RMG_PP_CHECKBOXES_LABEL     1351
#define IDC_RMG_CG_NODES_LABEL_BOTTOM   1352
#define IDC_RMG_CT_TEMPLATES_LABEL      1353
#define IDC_RMG_CT_TEMPLATES_LIST       1354
#define IDC_RMG_CG_DELIMITER_00         1355
#define IDC_RMG_CT_GRAPHS_LIST          1355
#define IDC_RMG_CC_DELIMITER_00         1356
#define IDC_RMG_CT_FIELDS_LIST          1356
#define IDC_RMG_CT_ADD_TEMPLATE_BUTTON  1357
#define IDC_RMG_CT_DELETE_TEMPLATE_BUTTON 1358
#define IDC_RMG_CT_VSO_LIST             1359
#define IDC_RMG_CT_GRAPHS_LABEL         1360
#define IDC_RMG_CT_VSO_LABEL            1361
#define IDC_RMG_CT_FIELDS_LABEL         1362
#define IDC_RMG_CT_SCRIPT_FILE_NAME_LABEL 1363
#define IDC_RMG_CT_SCRIPT_FILE_NAME_EDIT 1364
#define IDC_RMG_CT_SCRIPT_FILE_NAME_BROWSE_BUTTON 1365
#define IDC_RMG_CT_FORESTS_SOUNDS_LABEL 1366
#define IDC_RMG_CT_FORESTS_AMBIENT_SOUND_LABEL 1367
#define IDC_RMG_CT_FORESTS_CIRCLE_SOUND_LABEL 1368
#define IDC_RMG_CT_FORESTS_AMBIENT_SOUND_COMBO 1369
#define IDC_RMG_CT_DELIMITER_00         1370
#define IDC_RMG_CT_CHECK_TEMPLATES_BUTTON 1371
#define IDC_RMG_CT_TEMPLATE_UNITS_BUTTON 1372
#define IDC_RMG_CC_CHECK_CONTAINERS_BUTTON 1373
#define IDC_RMG_CT_PLACE_LABEL          1373
#define IDC_RMG_TGP_PATH_LABEL_LEFT     1374
#define IDC_RMG_CT_TEMPLATE_DIPLOMACY_BUTTON 1374
#define IDC_RMG_TGP_PATH_LABEL_RIGHT    1375
#define IDC_RMG_TGP_WEIGHT_LABEL        1376
#define IDC_RMG_TGP_WEIGHT_EDIT         1377
#define IDC_RMG_TGP_STATS_LABEL_LEFT    1378
#define IDC_PE_PP_POINT_Y_COORD_EDIT    1378
#define IDC_RMG_TGP_STATS_LABEL_RIGHT   1379
#define IDC_PE_PP_POINT_Y_COORD_LABEL_LEFT 1379
#define IDC_RMG_TGP_DELIMITER_00        1380
#define IDC_RMG_TVP_STATS_LABEL_LEFT    1381
#define IDC_RMG_TVP_STATS_LABEL_RIGHT   1382
#define IDC_RMG_TVP_DELIMITER_00        1383
#define IDC_RMG_TVP_PATH_LABEL_LEFT     1384
#define IDC_RMG_TVP_PATH_LABEL_RIGHT    1385
#define IDC_RMG_TVP_WEIGHT_LABEL        1386
#define IDC_RMG_TVP_WEIGHT_EDIT         1387
#define IDC_RMG_TVP_WIDTH_EDIT          1388
#define IDC_RMG_TFP_STATS_LABEL_LEFT    1388
#define IDC_RMG_TVP_WIDTH_LABEL         1389
#define IDC_RMG_TFP_STATS_LABEL_RIGHT   1389
#define IDC_RMG_TVP_OPACITY_EDIT        1390
#define IDC_RMG_TFP_DELIMITER_00        1390
#define IDC_RMG_TVP_OPACITY_LABEL       1391
#define IDC_RMG_TFP_PATH_LABEL_LEFT     1391
#define IDC_RMG_TFP_PATH_LABEL_RIGHT    1392
#define IDC_RMG_TFP_WEIGHT_LABEL        1393
#define IDC_RMG_TFP_WEIGHT_EDIT         1394
#define IDC_RMG_TFP_DEFAULT_CHECK_BOX   1395
#define IDC_RMG_CT_SAVE_BUTTON          1396
#define IDC_PL_POINTS_LIST              1397
#define IDC_PL_ADD_POINT_BUTTON         1398
#define IDC_PL_DELETE_POINT_BUTTON      1399
#define IDC_PL_POINT_PROPERTIES_BUTTON  1400
#define IDC_PE_PP_POINT_X_COORD_LABEL_LEFT 1401
#define IDC_PE_PP_POINT_X_COORD_LABEL_RIGHT 1402
#define IDC_PE_PP_POINT_Y_COORD_LABEL_RIGHT 1403
#define IDC_PE_PP_POINT_X_COORD_EDIT    1404
#define IDC_SO_OBJECTS_LIST             1405
#define IDC_SO_PLAYER_COMBO             1406
#define IDC_SO_DIRECTION_PLACE          1407
#define IDC_SO_DIRECTION_EDIT           1408
#define IDC_SO_FILTER_LABEL             1409
#define IDC_SO_FILTER_COMBO             1410
#define IDC_SO_ADD_FILTER_BUTTON        1411
#define IDC_SO_DELETE_FILTER_BUTTON     1412
#define IDC_SO_PLAYER_LABEL             1413
#define IDC_SO_DIRECTION_LABEL          1414
#define IDC_SO_DELIMITER_00             1415
#define IDC_SHADE_BRUSH_SIZE_LABEL      1416
#define IDC_SHADE_DELIMITER_00          1417
#define IDC_SHADE_DELIMITER_01          1418
#define IDC_SHADE_DELIMITER_02          1419
#define IDC_SHADE_MIN_LABEL_LEFT        1420
#define IDC_FIELD_DELIMITER_01          1420
#define IDC_TE_TILES_LABEL              1421
#define IDC_TE_TILES_LIST               1422
#define IDC_TE_TILES_TYPES_LABEL        1423
#define IDC_FIELD_DELIMITER_02          1423
#define IDC_TE_TILE_TYPES_LIST          1424
#define IDC_VO_BRIGDES_LIST             1425
#define IDC_TOOLS_DAMAGE_LABEL_LEFT     1426
#define IDC_TOOLS_DAMAGE_EDIT           1427
#define IDC_TOOLS_DELIMITER_00          1428
#define IDC_TOOLS_SA_LIST               1429
#define IDC_TOOLS_SA_DELETE_BUTTON      1430
#define IDC_GROUPS_LABEL                1431
#define IDC_TOOLS_DAMAGE_LABEL_RIGHT    1431
#define IDC_GROUPS_LIST                 1432
#define IDC_GROUPS_DELETE_BUTTON        1433
#define IDC_GROUPS_ADD_BUTTON           1434
#define IDC_GROUPS_PROPERTY_LABEL       1435
#define IDC_GROUPS_PROPERTY_LIST        1436
#define IDC_GROUPS_DELETE_PROPERTY_BUTTON 1437
#define IDC_AIG_DELIMITER_00            1438
#define IDC_AIG_MOBILE_REINFORCEMENT_SCRIPT_ID_LIST 1439
#define IDC_AIG_MOBILE_REINFORCEMENT_SCRIPT_ID_LABEL 1440
#define IDC_AIG_POSITIONS_LABEL         1441
#define IDC_AIG_POSITIONS_LIST          1442
#define IDC_AIG_ADD_MOBILE_REINFORCEMENT_SCRIPT_ID_BUTTON 1443
#define IDC_AIG_DELETE_MOBILE_REINFORCEMENT_SCRIPT_ID_BUTTON 1444
#define IDC_AIG_POSITION_TYPE_BUTTON    1445
#define IDC_AIG_DELIMITER_01            1446
#define IDC_AIG_MESSAGE_LABEL           1447
#define IDC_RMG_CT_PLACE_COMBO          1448
#define IDC_TAB_AI_GENERAL_ENTER_SCRIPT_ID_EDIT 1449
#define IDC_SO_DIPLOMACY_BUTTON         1450
#define IDC_SO_DIPLOMACY_ADD_BUTTON     1451
#define IDC_SO_DIPLOMACY_PLAYERS_LIST   1452
#define IDC_PCA_SET_BUTTON              1453
#define IDC_PCA_GOTO_BUTTON             1454
#define IDC_PCA_LIST                    1455
#define IDC_RMG_PP_PLACE_COMBO_BOX      1456
#define IDC_SO_DIPLOMACY_PLAYERS_LABEL  1457
#define IDC_SO_DIPLOMACY_TYPE_LABEL     1458
#define IDC_SO_DIPLOMACY_TYPE_COMBO_BOX 1459
#define IDC_CF_FILTERS_LIST             1460
#define IDC_SO_DIPLOMACY_ATTACK_SIDE_COMBO_BOX 1460
#define IDC_CF_ADD_FILTER_BUTTON        1461
#define IDC_SO_DIPLOMACY_ATTACK_SIDE_LABEL 1461
#define IDC_CF_DELETE_FILTER_BUTTON     1462
#define IDC_CF_FILTERS_LABEL            1463
#define IDC_CF_ALL_FOLDERS_LIST         1464
#define IDC_CF_ALL_FOLDERS_LABEL        1465
#define IDC_CF_CONDITIONS_LIST          1466
#define IDC_CF_ADD_CONDITION_BUTTON     1467
#define IDC_CF_CONDITIONS_LABEL         1468
#define IDC_CF_FILTER_NAME_LABEL        1468
#define IDC_CF_TS_ADD_SHELL             1468
#define IDC_CF_REMOVE_CONDITION_BUTTON  1469
#define IDC_CF_FILTER_NAME_EDIT         1469
#define IDC_CF_RENAME_FILTER_BUTTON     1470
#define IDC_CRM_DIRECTIONS_RADIOBUTTONS_LABEL 1470
#define IDC_CF_TS_REMOVE_SHELL          1470
#define IDC_CRM_DIRECTION_RADIO_0       1471
#define IDC_CRM_DIRECTION_RADIO_90      1472
#define IDC_CRM_DIRECTION_RADIO_180     1473
#define IDC_CRM_DIRECTION_RADIO_270     1474
#define IDC_CRM_LEVEL_RADIO_0           1475
#define IDC_CRM_LEVEL_RADIO_1           1476
#define IDC_CRM_LEVEL_RADIO_2           1477
#define IDC_CRM_LEVEL_RADIOBUTTONS_LABEL 1478
#define IDC_CRM_SAVE_AS_BZM_CHECKBOX    1479
#define IDC_CRM_SETTING_COMBOBOX        1480
#define IDC_SO_SET_FILTER_EDIT          1481
#define IDC_SO_SET_FILTER_EDIT_LABEL    1482
#define IDC_SO_SET_FILTER_LIST_LABEL    1483
#define IDC_GROUP_ID_EDIT               1484
#define IDC_GROUP_ID_LABEL              1485
#define IDC_AREA_NAME_EDIT              1486
#define IDC_AREA_NAME_LABEL             1487
#define IDC_SCRIPT_ID_EDIT              1488
#define IDC_SCRIPT_ID_STATIC            1489
#define IDC_SCRIPT_FILE_BROWSE_BUTTON   1490
#define IDC_SCRIPT_FILE_EDIT            1491
#define IDC_SCRIPT_FILE_LABEL           1492
#define IDC_NEW_MAP_SIZE_LABEL          1493
#define IDC_NEW_MAP_SIZE_X_LABEL        1493
#define IDC_NEW_MAP_NAME_LABEL          1494
#define IDC_NEW_MAP_SEASON_LABEL        1495
#define IDC_NEW_MAP_NAME_EDIT           1496
#define IDC_CRM_SAVE_AS_DDS_CHECKBOX    1497
#define IDC_NEW_MAP_SIZE_Y_LABEL        1497
#define IDC_MINIMAP_GAME_CREATE         1498
#define IDC_NEW_MAP_MOD_LABEL           1498
#define IDC_NEW_MAP_SQUARE_CHECK_BOX    1499
#define IDC_VO_FENCES_LIST_LABEL        1500
#define IDC_VO_BRIGDES_LIST_LABEL       1501
#define IDC_OPEN_MAP_NAME_LABEL         1502
#define IDC_OPEN_MAP_NAME_COMBO_BOX      1503
#define IDC_OPEN_MAP_NAME_BROWSE_BUTTON 1504
#define IDC_OPEN_MAP_MOD_LABEL          1505
#define IDC_OPEN_MAP_MOD_COMBO_BOX      1506
#define IDC_OPTIONS_COMMAND_LINE_LABEL  1507
#define IDC_OPTIONS_COMMAND_LINE_EDIT   1508
#define IDC_OPTIONS_DEF_EXTENTION_LABEL 1509
#define IDC_RMG_CT_MOD_LABEL            1510
#define IDC_RMG_CT_MOD_COMBO_BOX        1511
#define IDC_RMG_CF_DELIMITER_00         1512
#define IDC_RMG_CF_FIELDS_LABEL         1513
#define IDC_RMG_CF_FIELDS_LIST          1514
#define IDC_RMG_CF_ADD_FIELD_BUTTON     1515
#define IDC_RMG_CF_DELETE_FIELD_BUTTON  1516
#define IDC_RMG_CF_CHECK_FIELDS_BUTTON  1517
#define IDC_RMG_CF_FIELD_PROPERTIES_PLACEHOLDER 1518
#define IDC_RMG_CF_SAVE_BUTTON          1519
#define IDC_CF_TS_SEASON_LABEL          1520
#define IDC_CF_TS_AVAILABLE_TILES_LABEL 1521
#define IDC_CF_TS_SHELLS_LABEL          1522
#define IDC_CF_TS_TILES_LABEL           1523
#define IDC_CF_TS_ADD_TILE              1524
#define IDC_CF_TS_REMOVE_TILE           1525
#define IDC_CF_OS_OBJECTS_FILTER_LABEL  1526
#define IDC_CF_OS_OBJECTS_FILTER_COMBO  1527
#define IDC_CF_OS_AVAILABLE_OBJECTS_LABEL 1528
#define IDC_CF_OS_AVAILABLE_OBJECTS_LIST 1529
#define IDC_CF_OS_SHELLS_LABEL          1530
#define IDC_CF_OS_SHELLS_LIST           1531
#define IDC_CF_OS_OBJECTS_LABEL         1532
#define IDC_CF_OS_OBJECTS_LIST          1533
#define IDC_CF_OS_ADD_SHELL             1534
#define IDC_CF_OS_REMOVE_SHELL          1535
#define IDC_CF_OS_ADD_OBJECT            1536
#define IDC_CF_OS_REMOVE_OBJECT         1537
#define IDC_CF_H_PROFILE_LABEL          1538
#define IDC_CF_OS_OBJECT_PROPERTIES     1538
#define IDC_CF_H_HEIGHT_LABEL           1539
#define IDC_CF_OS_SHELL_PROPERTIES      1539
#define IDC_CF_H_HEIGHT_LABEL_LEFT      1539
#define IDC_CF_H_SIZE_MIN_LABEL         1540
#define IDC_CF_H_SIZE_MIN_LABEL_LEFT    1540
#define IDC_CF_H_SIZE_MAX_LABEL         1541
#define IDC_CF_H_SIZE_MAX_LABEL_LEFT    1541
#define IDC_CF_H_POSITIVE_RATIO_LABEL   1542
#define IDC_CF_H_PROFILE_EDIT           1543
#define IDC_CF_H_HEIGHT_EDIT            1544
#define IDC_CF_H_SIZE_MIN_EDIT          1545
#define IDC_CF_H_POSITIVE_RATIO_SLIDER_LABEL_LEFT 1546
#define IDC_CF_H_POSITIVE_RATIO_SLIDER_LABEL_RIGHT 1547
#define IDC_E_FRAME                     1548
#define IDC_E_IMAGE                     1549
#define IDC_CF_OS_LIST_RADIO            1550
#define IDC_CF_OS_THUMBNAILS_RADIO      1551
#define IDC_CF_TS_TILE_PROPERTIES       1552
#define IDC_RMG_CF_TS_TP_ICON           1553
#define IDC_RMG_CF_TS_TP_NAME_LABEL_LEFT 1554
#define IDC_RMG_CF_TS_TP_NAME_LABEL_RIGHT 1555
#define IDC_RMG_CF_TS_TP_WEIGHT_LABEL   1556
#define IDC_RMG_CF_TS_TP_WEIGHT_EDIT    1557
#define IDC_RMG_CF_TS_TP_DELIMITER_01   1558
#define IDC_RMG_CF_OS_OP_NAME_LABEL_LEFT 1559
#define IDC_RMG_CF_TS_TP_VARIANTS_LABEL_LEFT 1559
#define IDC_RMG_CF_OS_OP_WEIGHT_LABEL   1560
#define IDC_RMG_CF_TS_TP_VARIANTS_LABEL_RIGHT 1560
#define IDC_RMG_CF_OS_OP_DELIMITER_01   1561
#define IDC_RMG_CF_OS_OP_PATH_LABEL_LEFT 1562
#define IDC_RMG_CF_OS_OP_VIS_TYPE_LABEL_LEFT 1563
#define IDC_RMG_CF_OS_OP_GAME_TYPE_LABEL_LEFT 1564
#define IDC_RMG_CF_TS_TP_STATS_LABEL_LEFT 1565
#define IDC_RMG_CF_TS_TP_STATS_LABEL_RIGHT 1566
#define IDC_RMG_CF_TS_TP_DELIMITER_00   1567
#define IDC_RMG_CF_OS_OP_DELIMITER_00   1568
#define IDC_RMG_CF_OS_OP_STATS_LABEL_LEFT 1569
#define IDC_RMG_CF_OS_OP_STATS_LABEL_RIGHT 1570
#define IDC_RMG_CF_TS_WIDTH_LABEL_LEFT  1573
#define IDC_RMG_CF_TS_WIDTH_EDIT        1574
#define IDC_CF_TS_SHELL_PROPERTIES      1575
#define IDC_RMG_CF_OS_WIDTH_EDIT        1576
#define IDC_RMG_CF_OS_WIDTH_LABEL_LEFT  1577
#define IDC_RMG_CF_TS_WIDTH_LABEL_RIGHT 1578
#define IDC_RMG_CF_OS_STEP_EDIT         1578
#define IDC_RMG_CF_OS_STEP_LABEL_LEFT   1579
#define IDC_RMG_CF_OS_PROBABILITY_EDIT  1580
#define IDC_RMG_CF_OS_PROBABILITY_LABEL_LEFT 1581
#define IDC_RMG_CF_OS_WIDTH_LABEL_RIGHT 1582
#define IDC_RMG_CF_OS_STEP_LABEL_RIGHT  1583
#define IDC_RMG_CF_OS_PROBABILITY_LABEL_RIGHT 1584
#define IDC_CF_H_HEIGHT_LABEL_RIGHT     1585
#define IDC_CF_H_SIZE_MIN_LABEL_RIGHT   1586
#define IDC_CF_H_SIZE_MAX_LABEL_RIGHT   1587
#define IDC_FIELD_FILEDS_LABEL          1587
#define IDC_FIELD_DELIMITER_00          1589
#define IDC_FIELD_MIN_LENGTH_LABEL      1590
#define IDC_FIELD_MIN_LENGTH_EDIT       1591
#define IDC_FIELD_WIDTH_LABEL           1592
#define IDC_FIELD_WIDTH_EDIT            1593
#define IDC_FIELD_DISTURBANCE_LABEL     1594
#define IDC_FIELD_DISTURBANCE_EDIT      1595
#define IDC_BRUSHSIZE                   2000
#define IDC_TRANSPARENCE                2001
#define IDC_SHOW_FIRE_RANGE_FILTER      2002
#define IDC_PLAYER_NUMBER               2003
#define ID_INDICATOR_COORDS             3007
#define ID_INDICATOR_CONTROL            3008
#define ID_INDICATOR_TILEPOS            3009
#define ID_INDICATOR_OBJECTTYPE         3010
#define IDD_DIALOGPROPERTIE             3190
#define ID_GUI_VIEW                     5007
#define IDC_SO_LIST_LIST                10000
#define IDC_SO_LIST_ICONS               10001
#define ID_RECENT_MAP_0                 32100
#define ID_RECENT_MAP_1                 32101
#define ID_RECENT_MAP_2                 32102
#define ID_RECENT_MAP_3                 32103
#define ID_RECENT_MAP_4                 32104
#define ID_RECENT_MAP_5                 32105
#define ID_RECENT_MAP_6                 32106
#define ID_RECENT_MAP_7                 32107
#define ID_RECENT_MAP_8                 32108
#define ID_RECENT_MAP_9                 32109
#define ID_FILE_SAVEMAP2                32700
#define ID_VIEW_CONTROL_TOOLBAR         32772
#define ID_RUN_BUTTON                   32775
#define ID_ESCAPE                       32776
#define ID_STOP_BUTTON                  32777
#define ID_BUTTONPOPUPMENU_SETUSUALTEXTURE 32778
#define ID_SETDEFAULTTEXTURE            32779
#define ID_BUTTONPOPUPMENU_SETHIGHLIGHTEDTEXTURE 32780
#define ID_SETHIGHLIGHTEDTEXTURE        32781
#define ID_BUTTONPOPUPMENU_SETSELECTEDTEXTURE 32782
#define ID_SETSELECTEDTEXTURE           32783
#define ID_BUTTONPOPUPMENU_SETPOSITION  32784
#define ID_SETPOSITION                  32785
#define ID_ALIGNLEFT                    32787
#define ID_ALIGNTOP                     32789
#define ID_ALIGNRIGHT                   32791
#define ID_ALIGNBOTTOM                  32793
#define ID_SETEQUALSIZE                 32795
#define ID_CHECK_BUTTON_PROPERTIES      32795
#define ID_CHECK_BUTTON_STRING          32795
#define ID_PROPERTIES                   32796
#define ID_MINSCROLL_BUTTON_STRING      32796
#define ID_SHOW_PROPERTIES              32797
#define ID_MAXSCROLL_BUTTON_STRING      32797
#define ID_ALIGNMENU_CREATERADIOBUTTON  32798
#define ID_MENU_CREATENEWTEMPLATE       32799
#define ID_DELETE_TEMPLATE              32800
#define ID_TEMPLATE_PROPERTIES          32801
#define ID_FILE_LOAD                    32803
#define ID_SHOW_CONTROL_BAR             32804
#define ID_HELP_TESTBUTTON              32805
#define ID_TESTBUTTON                   32806
#define ID_COMPOSE_ANIM                 32807
#define ID_FILE_EXPORTPROJECT           32808
#define ID_FILE_EXPORTFILES             32809
#define ID_FILE_CREATENEWPROJECT        32810
#define ID_FILE_SAVEPROJECTAS           32812
#define ID_FILE_LOADMAP                 32813
#define ID_FILE_SAVEMAP                 32814
#define ID_FILE_EXPORTTOPICTURE         32815
#define ID_FILE_IMPORTFROMPICTURE       32816
#define ID_FILE_CLOSEPROJECT            32817
#define ID_BUTTONFILLAREA               32821
#define ID_INSERTTREEITEM_INSERTITEM    32823
#define ID_INSERT_TREE_ITEM             32824
#define ID_INTERPOLATE_TREE_ITEM        32825
#define ID_MOVE_OBJECT                  32826
#define ID_DRAW_GRID                    32827
#define ID_SET_ZERO_BUTTON              32828
#define ID_BUTTONUPDATE                 32829
#define ID_BUTTONFOG                    32831
#define ID_FILE_OPENOLDPROJECT          32832
#define ID_FILE_NEWMAP                  32833
#define ID_FILE_SETDIRECTORIES          32835
#define ID_FILE_BATCH_MODE              32837
#define ID_FILE_EXPORT_ONLY_RPG_STATS   32838
#define ID_TOOLS_CLEARCASH              32839
#define ID_KEYFRAMEZOOMMENU_ZOOMINX     32840
#define ID_KEYFRAME_ZOOMINX             32841
#define ID_KEYFRAME_ZOOMOUTX            32842
#define ID_KEYFRAME_ZOOMINY             32843
#define ID_KEYFRAME_ZOOMOUTY            32844
#define ID_DELETE_NODE                  32845
#define ID_RESET                        32846
#define ID_KEYFRAME_DELETE_NODE         32848
#define ID_KEYFRAME_RESET_ALL           32849
#define ID_GET_PARTICLE_INFO            32850
#define ID_EDIT_SETBACKGROUNDCOLOR      32851
#define ID_BUTTON_CAMERA                32852
#define ID_BUTTONAI                     32854
#define ID_BUTTONFIT                    32856
#define ID_BUTTON32858                  32858
#define ID_BUTTONADDTOGROUP             32859
#define ID_BUTTOSHOWINFO                32859
#define ID_SET_ENTRANCE_BUTTON          32860
#define ID_TOOLS_DELR                   32861
#define ID_DELETEELEMENT                32862
#define ID_CREATENEWTEMPLATE            32863
#define ID_CENTER_TILE                  32864
#define ID_FENCE_CENTER_ABOUT_TILE      32865
#define ID_CENTER_FENCE_ABOUT_TILE      32867
#define ID_BUTTONSHOWBOXES              32868
#define ID_SET_SHOOT_POINT              32869
#define ID_SET_SHOOT_ANGLE              32870
#define ID_SET_HORIZONTAL_SHOOT         32871
#define ID_OPTIONS                      32872
#define ID_BUTTONSETCAMERA              32873
#define ID_DRAW_TRANSPARENCE            32874
#define ID_DROPARROW                    32875
#define ID_DRAW_ONE_WAY_PASSABILITY     32875
#define ID_DRAW_PASS                    32878
#define ID_DRAW_ONE_WAY_TRANSEPARENCE   32880
#define ID_SHOWMINIMAP                  32881
#define ID_SHOW_FIRE_RANGE              32882
#define ID_NEW_FOREST                   32883
#define ID_SHOW_SCENE_0                 32884
#define ID_SHOW_SCENE_1                 32885
#define ID_SHOW_SCENE_2                 32886
#define ID_SHOW_SCENE_3                 32887
#define ID_SHOW_SCENE_4                 32888
#define ID_SHOW_SCENE_6                 32890
#define ID_SHOW_SCENE_7                 32891
#define ID_SHOW_SCENE_8                 32892
#define ID_SHOW_SCENE_9                 32893
#define ID_NEW_CONTAINER                32896
#define ID_ADD_START_COMMANDS           32897
#define ID_START_COMMANDS_LIST          32898
#define ID_RESERVE_POSITIONS            32899
#define ID_SHOW_SCENE_10                32900
#define ID_FILE_SAVEMAP_BINARY          32901
#define ID_FILE_SAVE_BINARY             32902
#define ID_SHOW_SCENE_11                32904
#define ID_SHOW_SCENE_12                32905
#define ID_SHOW_SCENE_14                32906
#define ID_EDIT_UNIT_CREATION_INFO      32907
#define IDC_RMG_CC_ADD_MENU             32910
#define IDC_RMG_CC_DELETE_MENU          32911
#define IDC_RMG_CC_PROPERTIES_MENU      32912
#define IDC_RMG_CC_ADD_CONTAINER_MENU   32913
#define IDC_RMG_CC_DELETE_CONTAINER_MENU 32914
#define IDC_RMG_CC_CONTAINER_PROPERTIES_MENU 32915
#define IDC_RMG_CG_ADD_GRAPH_MENU       32916
#define IDC_RMG_CG_DELETE_GRAPH_MENU    32917
#define IDC_RMG_CG_GRAPH_PROPERTIES_MENU 32918
#define ID_NEW_GRAPH                    32919
#define IDC_RMG_CG_DELETE_MENU          32920
#define IDC_RMG_CG_PROPERTIES_MENU      32921
#define IDC_RMG_GLP_DELETE_MENU         32922
#define ID_FILE_SAVEAS                  32925
#define ID_FILE_EXIT                    32926
#define ID_NEW_TEMPLATE                 32929
#define IDC_RMG_CT_ADD_TEMPLATE_MENU    32930
#define IDC_RMG_CT_DELETE_TEMPLATE_MENU 32931
#define IDC_RMG_CT_TEMPLATE_UNITS_MENU  32932
#define IDC_RMG_CT_GRAPH_PROPERTIES_MENU 32933
#define IDC_RMG_CT_ADD_GRAPH_MENU       32934
#define IDC_RMG_CT_DELETE_GRAPH_MENU    32935
#define IDC_RMG_CT_ADD_VSO_MENU         32936
#define IDC_RMG_CT_DELETE_VSO_MENU      32937
#define IDC_RMG_CT_VSO_PROPERTIES_MENU  32938
#define IDC_RMG_CT_ADD_FIELD_MENU       32939
#define IDC_RMG_CT_DELETE_FIELD_MENU    32940
#define IDC_RMG_CT_FIELD_PROPERTIES_MENU 32941
#define IDC_PE_PL_ADD_MENU              32943
#define IDC_PE_PL_DELETE_MENU           32944
#define IDC_PE_PL_PROPERTIES_MENU       32945
#define ID_SHOW_STORAGE_COVERAGE        32946
#define IDC_TAB_AIG_ADD_REINFORCEMENT_MENU 32947
#define IDC_TAB_AIG_DELETE_REINFORCEMENT_MENU 32948
#define IDC_TAB_AIG_POSITION_TYPE_MENU  32949
#define IDC_TAB_AIG_DELETE_POSITION_MENU 32950
#define TAB_SIMPLE_OBJECTS_DIPLOMACY_ADD_PLAYER_MENU 32951
#define TAB_SIMPLE_OBJECTS_DIPLOMACY_DELETE_PLAYER_MENU 32952
#define TAB_SIMPLE_OBJECTS_DIPLOMACY_SIDE_0_MENU 32953
#define TAB_SIMPLE_OBJECTS_DIPLOMACY_SIDE_1_MENU 32954
#define IDC_RMG_CT_TEMPLATE_DIPLOMACY_MENU 32955
#define IDC_CF_ADD_FILTER_MENU          32956
#define IDC_CF_DELETE_FILTER_MENU       32957
#define IDC_CF_RENAME_FILTER_MENU       32958
#define ID_FILE_CREATE_RANDOM_MISSION   32959
#define ID_VIEW_TOOLS_TOOLBAR           32960
#define ID_VIEW_LEFT_BAR                32961
#define ID_BUTTON32963                  32963
#define ID_DIPLOMACY                    32970
#define ID_FILTER_COMPOSER              32971
#define ID_TOOL_0                       32973
#define ID_VIEW_TOOLBAR_0               32974
#define ID_VIEW_TOOLBAR_1               32975
#define ID_VIEW_TOOLBAR_2               32976
#define ID_VIEW_TOOLBAR_3               32977
#define ID_VIEW_TOOLBAR_4               32978
#define ID_SHOW_SCENE_13                32981
#define ID_TOOL_1                       32982
#define IDC_SCP_EDIT_MENU               32985
#define IDC_SCP_DELETE_MENU             32986
#define ID_TOOL_2                       32987
#define ID_TOOL_3                       32988
#define ID_TOOL_4                       32989
#define ID_TOOLS_RUN_GAME               32990
#define ID_TOOLS_OPTIONS                32991
#define IDC_RMG_CF_ADD_FIELD_MENU       32992
#define IDC_RMG_CF_DELETE_FIELD_MENU    32993
#define ID_NEW_FIELD                    32994
#define IDC_CF_TS_ADD_TILE_MENU         32995
#define IDC_CF_TS_AVAILABLE_TILE_PROPERTIES_MENU 32996
#define IDC_CF_TS_REMOVE_TILE_MENU      32997
#define IDC_CF_TS_TILE_PROPERTIES_MENU  32998
#define ID_PLAYER_NUMBER                32999
#define IDC_CF_TS_ADD_SHELL_MENU        32999
#define IDC_CF_TS_REMOVE_SHELL_MENU     33000
#define IDC_CF_TS_SHELL_PROPERTIES_MENU 33001
#define IDC_CF_OS_ADD_OBJECT_MENU       33002
#define IDC_CF_OS_AVAILABLE_OBJECT_PROPERTIES_MENU 33003
#define IDC_CF_OS_REMOVE_OBJECT_MENU    33004
#define IDC_CF_OS_OBJECT_PROPERTIES_MENU 33005
#define IDC_CF_OS_ADD_SHELL_MENU        33006
#define IDC_CF_OS_REMOVE_SHELL_MENU     33007
#define IDC_CF_OS_SHELL_PROPERTIES_MENU 33008
#define IDC_TE_TILE_PROPERTIES_MENU     33009
#define IDC_SO_OBJECT_PROPERTIES_MENU   33010
#define ID_FILE_SAVE_XML                33011
#define ID_FILE_SAVE_BZM                33012
#define IDC_SCP_ADD_MENU                33017
#define IDS_REGISTRY_PATH               61206
#define IDS_TOOLBAR_KEY                 61207
#define IDS_WINDOWBAR_KEY               61208
#define IDS_ERR_DIR_PREFIX              61216
#define ID_BRUSH                        61217
#define ID_SHOW_FIRE_RANGE_FILTER       61219
#define IDS_RECENT_MAP                  61222
#define IDS_NO_HELP_FILE_TITLE          61268
#define IDS_NO_HELP_FILE_MESSAGE        61269
#define IDS_COMMAND                     61270
#define IDS_TOOLBAR_FILE                61271
#define IDS_TOOLBAR_SETTINGS            61272
#define IDS_TOOLBAR_MAP                 61273
#define IDS_TOOLBAR_LAYERS              61274
#define IDS_TOOLBAR_UNIT                61275
#define IDS_TOOLBAR_VIEW                61276
#define IDS_TOOLBAR_MENU                61277
#define IDS_MAP_NAME_INVALID            61278
#define IDS_INVALID_FIELD_SEASON        61279

#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        396
#define _APS_NEXT_COMMAND_VALUE         33018
#define _APS_NEXT_CONTROL_VALUE         1596
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
