#pragma once
// Mirror of the ETreeItemType constants from Sources/src/editor/TreeItem.h for
// the 11 stats-only sub-editors T02 ports. Values must match the MFC enum
// byte-for-byte so a shared ETreeItemType between the ports (eg. in a sidecar
// written by one editor and read by the other) survives. The authoritative
// source is Sources/src/editor/TreeItem.h; this header exists to keep the port
// headers from pulling in MFC/windows types transitively.

namespace NResourceModel
{

// base = 0x11000000 (EDITOR_TREE_BASE_VALUE); offsets copied verbatim.
enum ETreeItemType
{
	ETIT_BASE = 0x11000000,

	// Infantry (Unit/Animation) sub-editor - root tag "Unit_Composer_Project".
	// Despite the "unt" fixture extension this editor is the Infantry sub-editor
	// per MEM005 and CParentFrame subclass AnimFrm.cpp.
	ETIT_ANIMATION_ROOT_ITEM      = ETIT_BASE +  1,
	ETIT_UNIT_COMMON_PROPS_ITEM   = ETIT_BASE +  2,
	ETIT_LOCALIZATION_ITEM        = ETIT_BASE +  3,	// shared: localization.h
	ETIT_UNIT_AI_PROPS_ITEM       = ETIT_BASE +  4,
	ETIT_UNIT_WEAPON_PROPS_ITEM   = ETIT_BASE +  5,
	ETIT_UNIT_GRENADE_PROPS_ITEM  = ETIT_BASE +  6,
	ETIT_UNIT_DIRECTORY_PROPS_ITEM= ETIT_BASE +  7,
	ETIT_UNIT_SEASON_PROPS_ITEM   = ETIT_BASE +  8,
	ETIT_UNIT_DIRECTORIES_ITEM    = ETIT_BASE +  9,
	ETIT_UNIT_ANIMATIONS_ITEM     = ETIT_BASE + 10,
	ETIT_UNIT_ANIMATION_PROPS_ITEM= ETIT_BASE + 11,
	ETIT_UNIT_FRAME_PROPS_ITEM    = ETIT_BASE + 12,
	ETIT_UNIT_ACTIONS_ITEM        = ETIT_BASE + 13,
	ETIT_UNIT_ACTION_PROPS_ITEM   = ETIT_BASE + 14,
	ETIT_UNIT_EXPOSURES_ITEM      = ETIT_BASE + 15,
	ETIT_UNIT_ACKS_ITEM           = ETIT_BASE + 16,
	ETIT_UNIT_ACK_TYPES_ITEM      = ETIT_BASE + 17,
	ETIT_UNIT_ACK_TYPE_PROPS_ITEM = ETIT_BASE + 18,

	// Sprite - root tag "Sprite_Composer_Project".
	ETIT_SPRITE_ROOT_ITEM         = ETIT_BASE + 21,
	ETIT_SPRITES_ITEM             = ETIT_BASE + 22,
	ETIT_SPRITE_PROPS_ITEM        = ETIT_BASE + 23,

	// Object - root tag "Object_Composer_Project".
	ETIT_OBJECT_ROOT_ITEM         = ETIT_BASE + 51,
	ETIT_OBJECT_COMMON_PROPS_ITEM = ETIT_BASE + 52,
	ETIT_OBJECT_GRAPHICS_ITEM     = ETIT_BASE + 53,
	ETIT_OBJECT_SPRITE_PROPS_ITEM = ETIT_BASE + 54,
	ETIT_OBJECT_SHADOW_PROPS_ITEM = ETIT_BASE + 55,
	ETIT_OBJECT_PARTICLES_ITEM    = ETIT_BASE + 56,
	ETIT_OBJECT_PASSES_ITEM       = ETIT_BASE + 57,
	ETIT_OBJECT_PASS_PROPS_ITEM   = ETIT_BASE + 58,
	ETIT_OBJECT_GRAPHIC1_PROPS_ITEM  = ETIT_BASE + 273,
	ETIT_OBJECT_GRAPHICW1_PROPS_ITEM = ETIT_BASE + 274,
	ETIT_OBJECT_EFFECTS_ITEM         = ETIT_BASE + 275,
	ETIT_OBJECT_GRAPHICA1_PROPS_ITEM = ETIT_BASE + 276,

	// Mesh (Unit) - root tag "Mesh_Composer_Project".
	ETIT_MESH_ROOT_ITEM           = ETIT_BASE + 61,
	ETIT_MESH_COMMON_PROPS_ITEM   = ETIT_BASE + 62,
	ETIT_MESH_DEFENCES_ITEM       = ETIT_BASE + 63,
	ETIT_MESH_DEFENCE_PROPS_ITEM  = ETIT_BASE + 64,
	ETIT_MESH_GRAPHICS_ITEM       = ETIT_BASE + 65,
	ETIT_MESH_EFFECTS_ITEM        = ETIT_BASE + 67,
	ETIT_MESH_DEATH_CRATERS_ITEM  = ETIT_BASE + 68,
	ETIT_MESH_DEATH_CRATER_PROPS_ITEM = ETIT_BASE + 69,
	ETIT_MESH_TRACK_ITEM          = ETIT_BASE + 70,
	ETIT_MESH_PLATFORMS_ITEM      = ETIT_BASE + 71,
	ETIT_MESH_PLATFORM_PROPS_ITEM = ETIT_BASE + 72,
	ETIT_MESH_GUNS_ITEM           = ETIT_BASE + 73,
	ETIT_MESH_GUN_PROPS_ITEM      = ETIT_BASE + 74,
	ETIT_MESH_JOGGINGS_ITEM       = ETIT_BASE + 75,
	ETIT_MESH_JOGGING_PROPS_ITEM  = ETIT_BASE + 76,
	ETIT_MESH_LOCATORS_ITEM       = ETIT_BASE + 77,
	ETIT_MESH_LOCATOR_PROPS_ITEM  = ETIT_BASE + 78,
	ETIT_MESH_AVIA_ITEM           = ETIT_BASE + 79,
	ETIT_MESH_SOUND_PROPS_ITEM    = ETIT_BASE + 80,

	// Weapon - root tag "Weapon_Composer_Project".
	ETIT_WEAPON_ROOT_ITEM         = ETIT_BASE + 81,
	ETIT_WEAPON_COMMON_PROPS_ITEM = ETIT_BASE + 82,
	ETIT_WEAPON_SHOOT_TYPES_ITEM  = ETIT_BASE + 83,
	ETIT_WEAPON_DAMAGE_PROPS_ITEM = ETIT_BASE + 84,
	ETIT_WEAPON_SOUND_PROPS_ITEM  = ETIT_BASE + 85,
	ETIT_WEAPON_EFFECTS_ITEM      = ETIT_BASE + 86,
	ETIT_WEAPON_EFFECT_PROPS_ITEM = ETIT_BASE + 87,
	ETIT_WEAPON_FLASH_PROPS_ITEM  = ETIT_BASE + 88,
	ETIT_WEAPON_CRATERS_ITEM      = ETIT_BASE + 281,
	ETIT_WEAPON_CRATER_PROPS_ITEM = ETIT_BASE + 282,

	// Building - root tag "Building_Composer_Project".
	ETIT_BUILDING_ROOT_ITEM           = ETIT_BASE + 91,
	ETIT_BUILDING_COMMON_PROPS_ITEM   = ETIT_BASE + 92,
	ETIT_BUILDING_ENTRANCES_ITEM      = ETIT_BASE + 93,
	ETIT_BUILDING_ENTRANCE_PROPS_ITEM = ETIT_BASE + 94,
	ETIT_BUILDING_SLOTS_ITEM          = ETIT_BASE + 95,
	ETIT_BUILDING_SLOT_PROPS_ITEM     = ETIT_BASE + 96,
	ETIT_BUILDING_GRAPHICS_ITEM       = ETIT_BASE + 97,
	ETIT_BUILDING_GRAPHIC1_PROPS_ITEM = ETIT_BASE + 98,
	ETIT_BUILDING_GRAPHIC2_PROPS_ITEM = ETIT_BASE + 99,
	ETIT_BUILDING_GRAPHIC3_PROPS_ITEM = ETIT_BASE + 100,
	ETIT_BUILDING_DEFENCES_ITEM       = ETIT_BASE + 89,
	ETIT_BUILDING_DEFENCE_PROPS_ITEM  = ETIT_BASE + 90,
	ETIT_BUILDING_SUMMER_PROPS_ITEM   = ETIT_BASE + 261,
	ETIT_BUILDING_WINTER_PROPS_ITEM   = ETIT_BASE + 262,
	ETIT_BUILDING_GRAPHICW1_PROPS_ITEM= ETIT_BASE + 263,
	ETIT_BUILDING_GRAPHICW2_PROPS_ITEM= ETIT_BASE + 264,
	ETIT_BUILDING_GRAPHICW3_PROPS_ITEM= ETIT_BASE + 265,
	ETIT_BUILDING_PASSES_ITEM         = ETIT_BASE + 266,
	ETIT_BUILDING_PASS_PROPS_ITEM     = ETIT_BASE + 267,
	ETIT_BUILDING_FIRE_POINTS_ITEM    = ETIT_BASE + 268,
	ETIT_BUILDING_FIRE_POINT_PROPS_ITEM     = ETIT_BASE + 269,
	ETIT_BUILDING_DIR_EXPLOSIONS_ITEM       = ETIT_BASE + 270,
	ETIT_BUILDING_DIR_EXPLOSION_PROPS_ITEM  = ETIT_BASE + 271,
	ETIT_BUILDING_SMOKES_ITEM         = ETIT_BASE + 260,
	ETIT_BUILDING_SMOKE_PROPS_ITEM    = ETIT_BASE + 272,

	// Fence - root tag "Fence_Composer_Project".
	ETIT_FENCE_ROOT_ITEM          = ETIT_BASE + 121,
	ETIT_FENCE_COMMON_PROPS_ITEM  = ETIT_BASE + 122,
	ETIT_FENCE_DIRECTION_ITEM     = ETIT_BASE + 123,
	ETIT_FENCE_INSERT_ITEM        = ETIT_BASE + 124,
	ETIT_FENCE_PROPS_ITEM         = ETIT_BASE + 125,

	// Trench - root tag "Trench_Composer_Project".
	ETIT_TRENCH_ROOT_ITEM         = ETIT_BASE + 151,
	ETIT_TRENCH_COMMON_PROPS_ITEM = ETIT_BASE + 152,
	ETIT_TRENCH_SOURCES_ITEM      = ETIT_BASE + 153,
	ETIT_TRENCH_SOURCE_PROPS_ITEM = ETIT_BASE + 154,
	ETIT_TRENCH_DEFENCES_ITEM     = ETIT_BASE + 155,
	ETIT_TRENCH_DEFENCE_PROPS_ITEM= ETIT_BASE + 156,

	// Squad - root tag "Squad_Composer_Project".
	ETIT_SQUAD_ROOT_ITEM          = ETIT_BASE + 161,
	ETIT_SQUAD_COMMON_PROPS_ITEM  = ETIT_BASE + 162,
	ETIT_SQUAD_MEMBERS_ITEM       = ETIT_BASE + 163,
	ETIT_SQUAD_MEMBER_PROPS_ITEM  = ETIT_BASE + 164,
	ETIT_SQUAD_FORMATIONS_ITEM    = ETIT_BASE + 165,
	ETIT_SQUAD_FORMATION_PROPS_ITEM = ETIT_BASE + 166,

	// Mine - root tag "Mine_Composer_Project".
	ETIT_MINE_ROOT_ITEM           = ETIT_BASE + 210,
	ETIT_MINE_COMMON_PROPS_ITEM   = ETIT_BASE + 211,

	// Bridge - root tag "Bridge_Composer_Project".
	ETIT_BRIDGE_ROOT_ITEM         = ETIT_BASE + 220,
	ETIT_BRIDGE_COMMON_PROPS_ITEM = ETIT_BASE + 221,
	ETIT_BRIDGE_BEGIN_SPANS_ITEM  = ETIT_BASE + 222,
	ETIT_BRIDGE_CENTER_SPANS_ITEM = ETIT_BASE + 223,
	ETIT_BRIDGE_END_SPANS_ITEM    = ETIT_BASE + 224,
	ETIT_BRIDGE_PARTS_ITEM        = ETIT_BASE + 225,
	ETIT_BRIDGE_PART_PROPS_ITEM   = ETIT_BASE + 226,
	ETIT_BRIDGE_STAGE_PROPS_ITEM  = ETIT_BASE + 227,
	ETIT_BRIDGE_DEFENCES_ITEM     = ETIT_BASE + 228,
	ETIT_BRIDGE_DEFENCE_PROPS_ITEM= ETIT_BASE + 229,
	ETIT_BRIDGE_FIRE_POINTS_ITEM          = ETIT_BASE + 330,
	ETIT_BRIDGE_FIRE_POINT_PROPS_ITEM     = ETIT_BASE + 331,
	ETIT_BRIDGE_DIR_EXPLOSIONS_ITEM       = ETIT_BASE + 332,
	ETIT_BRIDGE_DIR_EXPLOSION_PROPS_ITEM  = ETIT_BASE + 333,
	ETIT_BRIDGE_SMOKES_ITEM               = ETIT_BASE + 334,
	ETIT_BRIDGE_SMOKE_PROPS_ITEM          = ETIT_BASE + 335,

	// Effect sub-editor - root tag "Effect_Composer_Project".
	ETIT_EFFECT_ROOT_ITEM            = ETIT_BASE + 31,
	ETIT_EFFECT_COMMON_PROPS_ITEM    = ETIT_BASE + 32,
	ETIT_EFFECT_ANIMATIONS_ITEM      = ETIT_BASE + 33,
	ETIT_EFFECT_MESHES_ITEM          = ETIT_BASE + 34,
	ETIT_EFFECT_FUNC_PARTICLES_ITEM  = ETIT_BASE + 35,
	ETIT_EFFECT_MAYA_PARTICLES_ITEM  = ETIT_BASE + 36,
	ETIT_EFFECT_LIGHTS_ITEM          = ETIT_BASE + 37,
	ETIT_EFFECT_ANIMATION_PROPS_ITEM = ETIT_BASE + 38,
	ETIT_EFFECT_MESH_PROPS_ITEM      = ETIT_BASE + 39,
	ETIT_EFFECT_FUNC_PROPS_ITEM      = ETIT_BASE + 40,
	ETIT_EFFECT_MAYA_PROPS_ITEM      = ETIT_BASE + 41,

	// TileSet sub-editor - root tag "TileSet_Composer_Project".
	ETIT_TILESET_ROOT_ITEM            = ETIT_BASE + 101,
	ETIT_TILESET_COMMON_PROPS_ITEM    = ETIT_BASE + 102,
	ETIT_TILESET_TERRAINS_ITEM        = ETIT_BASE + 103,
	ETIT_TILESET_TERRAIN_PROPS_ITEM   = ETIT_BASE + 104,
	ETIT_TILESET_TILE_PROPS_ITEM      = ETIT_BASE + 105,
	ETIT_CROSSETS_ITEM                = ETIT_BASE + 106,
	ETIT_CROSSET_PROPS_ITEM           = ETIT_BASE + 107,
	ETIT_CROSSET_TILES_ITEM           = ETIT_BASE + 108,
	ETIT_CROSSET_TILE_PROPS_ITEM      = ETIT_BASE + 109,
	ETIT_TILESET_TILES_ITEM           = ETIT_BASE + 320,
	ETIT_TILESET_LSOUNDS_ITEM         = ETIT_BASE + 321,
	ETIT_TILESET_ASOUNDS_ITEM         = ETIT_BASE + 322,
	ETIT_TILESET_LSOUND_PROPS_ITEM    = ETIT_BASE + 323,
	ETIT_TILESET_ASOUND_PROPS_ITEM    = ETIT_BASE + 324,

	// Keyframe generic base + Particle sub-editor - root tag
	// "Particle_Composer_Project".
	ETIT_KEYFRAME_TREE_ITEM                 = ETIT_BASE + 130,
	ETIT_PARTICLE_ROOT_ITEM                 = ETIT_BASE + 131,
	ETIT_PARTICLE_COMMON_PROPS_ITEM         = ETIT_BASE + 132,
	ETIT_PARTICLE_SOURCE_PROP_ITEMS         = ETIT_BASE + 133,
	ETIT_PARTICLE_GENERATE_SPIN_ITEM        = ETIT_BASE + 134,
	ETIT_PARTICLE_GENERATE_AREA_ITEM        = ETIT_BASE + 135,
	ETIT_PARTICLE_GENERATE_ANGLE_ITEM       = ETIT_BASE + 136,
	ETIT_PARTICLE_GENERATE_OPACITY_ITEM     = ETIT_BASE + 137,
	ETIT_PARTICLE_GENERATE_SPEED_ITEM       = ETIT_BASE + 138,
	ETIT_PARTICLE_GENERATE_LIFE_ITEM        = ETIT_BASE + 139,
	ETIT_PARTICLE_GENERATE_DENSITY_ITEM     = ETIT_BASE + 140,
	ETIT_PARTICLE_PROP_ITEMS                = ETIT_BASE + 141,
	ETIT_PARTICLE_SPIN_ITEM                 = ETIT_BASE + 142,
	ETIT_PARTICLE_WEIGHT_ITEM               = ETIT_BASE + 143,
	ETIT_PARTICLE_SPEED_ITEM                = ETIT_BASE + 144,
	ETIT_PARTICLE_SIZE_ITEM                 = ETIT_BASE + 145,
	ETIT_PARTICLE_OPACITY_ITEM              = ETIT_BASE + 146,
	ETIT_PARTICLE_GENERATE_RANDOM_SPIN_ITEM = ETIT_BASE + 147,
	ETIT_PARTICLE_TEXTURE_FRAME_ITEM        = ETIT_BASE + 148,
	ETIT_PARTICLE_COMPLEX_SOURCE_ITEM       = ETIT_BASE + 149,
	ETIT_PARTICLE_RAND_LIFE_ITEM            = ETIT_BASE + 340,
	ETIT_PARTICLE_RAND_SPEED_ITEM           = ETIT_BASE + 341,
	ETIT_PARTICLE_COMPLEX_ITEM              = ETIT_BASE + 342,
	ETIT_PARTICLE_C_RANDOM_SPEED_ITEM       = ETIT_BASE + 343,

	// GUI sub-editor - root tag "GUI_Composer_Project".
	ETIT_GUI_ROOT_ITEM             = ETIT_BASE + 171,
	ETIT_GUI_MOUSE_SELECT_ITEM     = ETIT_BASE + 172,
	ETIT_STATICS_TREE_ITEM         = ETIT_BASE + 174,
	ETIT_BUTTONS_TREE_ITEM         = ETIT_BASE + 175,
	ETIT_SLIDERS_TREE_ITEM         = ETIT_BASE + 176,
	ETIT_SCROLLBARS_TREE_ITEM      = ETIT_BASE + 177,
	ETIT_STATUSBARS_TREE_ITEM      = ETIT_BASE + 178,
	ETIT_LISTS_TREE_ITEM           = ETIT_BASE + 179,
	ETIT_DIALOGS_TREE_ITEM         = ETIT_BASE + 180,
	ETIT_UNKNOWNS_UI_TREE_ITEM     = ETIT_BASE + 181,
	ETIT_STATIC_PROPS_TREE_ITEM    = ETIT_BASE + 192,
	ETIT_BUTTON_PROPS_TREE_ITEM    = ETIT_BASE + 193,
	ETIT_SLIDER_PROPS_TREE_ITEM    = ETIT_BASE + 194,
	ETIT_SCROLLBAR_PROPS_TREE_ITEM = ETIT_BASE + 195,
	ETIT_STATUSBAR_PROPS_TREE_ITEM = ETIT_BASE + 196,
	ETIT_LIST_PROPS_TREE_ITEM      = ETIT_BASE + 197,
	ETIT_DIALOG_PROPS_TREE_ITEM    = ETIT_BASE + 198,

	// Mission sub-editor - root tag "Mission_Composer_Project".
	ETIT_MISSION_ROOT_ITEM           = ETIT_BASE + 230,
	ETIT_MISSION_COMMON_PROPS_ITEM   = ETIT_BASE + 231,
	ETIT_MISSION_OBJECTIVES_ITEM     = ETIT_BASE + 232,
	ETIT_MISSION_OBJECTIVE_PROPS_ITEM= ETIT_BASE + 233,
	ETIT_MISSION_MUSICS_ITEM         = ETIT_BASE + 234,
	ETIT_MISSION_MUSIC_PROPS_ITEM    = ETIT_BASE + 235,

	// Chapter sub-editor - root tag "Chapter_Composer_Project".
	ETIT_CHAPTER_ROOT_ITEM           = ETIT_BASE + 240,
	ETIT_CHAPTER_COMMON_PROPS_ITEM   = ETIT_BASE + 241,
	ETIT_CHAPTER_MISSIONS_ITEM       = ETIT_BASE + 242,
	ETIT_CHAPTER_MISSION_PROPS_ITEM  = ETIT_BASE + 243,
	ETIT_CHAPTER_PLACES_ITEM         = ETIT_BASE + 246,
	ETIT_CHAPTER_PLACE_PROPS_ITEM    = ETIT_BASE + 247,

	// Campaign sub-editor - root tag "Campaign_Composer_Project".
	ETIT_CAMPAIGN_ROOT_ITEM            = ETIT_BASE + 250,
	ETIT_CAMPAIGN_COMMON_PROPS_ITEM    = ETIT_BASE + 251,
	ETIT_CAMPAIGN_CHAPTERS_ITEM        = ETIT_BASE + 252,
	ETIT_CAMPAIGN_CHAPTER_PROPS_ITEM   = ETIT_BASE + 253,
	ETIT_CAMPAIGN_TEMPLATES_ITEM       = ETIT_BASE + 254,
	ETIT_CAMPAIGN_TEMPLATE_PROPS_ITEM  = ETIT_BASE + 255,

	// 3dRoad sub-editor - root tag "Road3D_Composer_Project".
	ETIT_3DROAD_ROOT_ITEM          = ETIT_BASE + 290,
	ETIT_3DROAD_COMMON_PROPS_ITEM  = ETIT_BASE + 291,
	ETIT_3DROAD_LAYER_PROPS_ITEM   = ETIT_BASE + 292,

	// 3dRiver sub-editor - root tag "River3D_Composer_Project".
	ETIT_3DRIVER_ROOT_ITEM             = ETIT_BASE + 300,
	ETIT_3DRIVER_LAYER_PROPS_ITEM      = ETIT_BASE + 301,
	ETIT_3DRIVER_BOTTOM_LAYER_PROPS_ITEM = ETIT_BASE + 302,
	ETIT_3DRIVER_LAYERS_ITEM           = ETIT_BASE + 303,

	// Medal sub-editor - root tag "Medal_Composer_Project".
	ETIT_MEDAL_ROOT_ITEM           = ETIT_BASE + 310,
	ETIT_MEDAL_COMMON_PROPS_ITEM   = ETIT_BASE + 311,
	ETIT_MEDAL_PICTURE_PROPS_ITEM  = ETIT_BASE + 312,
	ETIT_MEDAL_TEXT_PROPS_ITEM     = ETIT_BASE + 313
};

}
