#ifndef __MSXMLIMPORT_H__
#define __MSXMLIMPORT_H__
#pragma once
#ifdef __clang__
// Clang cannot process #import of type libraries; use the MSVC-pregenerated
// type library headers instead (msxml3.tlh/.tli, generated by the #import below).
#include "msxml3.tlh"
#else
#import "msxml3.dll" exclude("ISequentialStream", "_FILETIME")
#endif
using namespace MSXML2;
#endif // __MSXMLIMPORT_H__
