#ifndef __STREAMIO_TYPES_H__
#define __STREAMIO_TYPES_H__
enum
{
	STREAMIO_BASE_VALUE				= 0x100b0000,
	STREAMIO_STREAMIO					= STREAMIO_BASE_VALUE + 1,
	STREAMIO_MEMORY_STREAM		= STREAMIO_BASE_VALUE + 4,
	STREAMIO_RANDOM_GEN_SEED	= STREAMIO_BASE_VALUE + 5,

	STREAMIO_FORCED_DWORD	= 0x7fffffff
};
#endif // __STREAMIO_TYPES_H__
