#define IDAPPLY                         3
#define IDD_ABOUTBOX                    100
#define IDR_LISTBAR                     101
#define IDD_MULTITREECONRTOL_DIALOG     102
#define IDR_TREE_DOCKBAR                102
#define IDC_TEMPLATE_TREE               103
#define IDR_MAINFRAME                   128
#define IDR_MENU_BUTTONS                128
#define IDR_GUI_EDITOR                  129
#define IDR_EDITORTYPE                  129
#define IDR_ANIMATIONS_EDITOR           130
#define IDR_TEMPLATE_EDITOR             131
#define IDR_SPRITE_EDITOR               132
#define IDR_EFFECT_EDITOR               133
#define IDR_OBJECT_EDITOR               134
#define IDR_MESH_EDITOR                 135
#define IDR_WEAPON_EDITOR               136
#define IDR_BUILDING_EDITOR             137
#define IDR_TILE_EDITOR                 138
#define IDR_ROAD_EDITOR                 139
#define IDR_FENCE_EDITOR                140
#define IDR_PARTICLE_EDITOR             141
#define IDR_TRENCH_EDITOR               142
#define IDR_SQUAD_EDITOR                143
#define IDR_MINE_EDITOR                 144
#define IDR_BRIDGE_EDITOR               145
#define IDR_MISSION_EDITOR              146
#define IDR_CHAPTER_EDITOR              147
#define IDR_CAMPAIGN_EDITOR             148
#define IDR_3DROAD_EDITOR               149
#define IDR_3DRIVER_EDITOR              150
#define IDR_MEDAL_EDITOR                151
#define ID_TOOLS_CUSTOMIZE              200
#define IDS_COMMANDS                    201
#define IDR_CONTROL_TOOLBAR             250
#define IDC_MOVE_OBJECT_CURSOR          254
#define IDB_RADIOBUTTON                 255
#define IDB_BUTTON                      256
#define IDI_MOUSE                       261
#define IDR_BUTTON_MENU                 264
#define IDR_ADD_TEMPLATE_MENU           264
#define IDR_ALIGN_MENU                  265
#define IDD_SELECT_TEXTURE              266
#define IDB_DIALOG                      267
#define IDD_BUTTON_PROPERTIES           270
#define IDB_STATIC                      271
#define IDD_STATIC_PROPERTIES           272
#define IDD_SIMPLE_PROPERTIES           274
#define IDB_SLIDER                      276
#define IDD_SLIDER_PROPERTIES           277
#define IDB_SCROLL_BAR                  278
#define IDB_LIST_CONTROL                279
#define IDD_LIST_PROPERTIES             280
#define IDR_TEMPLATE_MENU               281
#define IDB_EDIT_LINE                   282
#define IDD_DIALOG2                     284
#define IDB_TREEBMP                     288
#define IDR_TOOLBAR1                    292
#define IDD_DIALOG3                     294
#define IDD_REFERENCE_DIALOG            294
#define IDB_CHECK_BMP                   295
#define IDR_MAPEDITORTOOLBAR            298
#define IDD_DIALOGFILLAREA              300
#define IDR_INSERT_TREE_ITEM_MENU       302
#define IDR_INTERPOLATE_TREE_ITEM_MENU  303
#define IDD_DIALOG4                     304
#define IDD_DIALOG1                     305
#define IDR_OBJECTTOOLBAR               308
#define IDD_DIALOG5                     310
#define IDD_DIALOGNEWMAP                312
#define IDD_SET_DIRECTORIES_DIALOG      313
#define IDD_DIALOG6                     314
#define IDD_DIALOGSHADE                 315
#define IDD_DIALOGFILTEREDITOR          316
#define IDD_DIALOG7                     317
#define IDD_DIALOG8                     318
#define IDD_RUN_BATCH_MODE_DIALOG       319
#define IDB_PUSHPIN                     321
#define IDD_DIALOG9                     323
#define IDD_DIALOGPROPERTIE2            324
#define IDR_KEYFRAME_ZOOM_MENU          325
#define IDD_DIALOGTOOLS                 326
#define IDD_DIALOG10                    327
#define IDD_GROUPMANAGER                329
#define IDD_DIALOG11                    331
#define IDC_ADD                         336
#define IDC_CURSOR1                     337
#define IDD_PROGRESS_DIALOG             338
#define IDD_DIALOG12                    339
#define IDD_DIALOGINSERTBYGROUPID       340
#define IDD_DIALOGFENCESETUP            341
#define IDD_DIALOGTREHCHSETUP           342
#define IDB_EDITOR_STARTUP              344
#define IDD_DIALOG13                    345
#define IDD_DIALOGOPTIONS               348
#define IDD_DIALOG14                    349
#define IDD_DIALOGENTERAREAMAP          350
#define IDD_RIVERSETUP                  351
#define IDD_ADVANCEDIALOG               353
#define IDD_BRIDGESETUP                 354
#define IDD_OPTION                      355
#define IDD_PASTENAME                   356
#define IDD_MINIMAPDIALOG               357
#define IDD_MULTY_SEL_DIALOG            360
#define IDR_TILESET_TOOLBAR             361
#define IDR_MESH_TOOLBAR                363
#define IDR_PARTICLE_TOOLBAR            365
#define IDR_FENCE_TOOLBAR               367
#define IDR_BUILDING_TOOLBAR            369
#define IDR_BRIDGE_TOOLBAR              371
#define IDD_SET_PICTURE_OPTIONS         373
#define IDR_SQUAD_TOOLBAR               375
#define IDR_ACK_MENU                    377
#define IDR_3DROAD_TOOLBAR              378
#define IDR_CHAPTER_TOOLBAR             380
#define IDR_EFFECT_TOOLBAR              382
#define IDR_INFANTRY_TOOLBAR            384
#define IDD_BROWSE_DIALOG               386
#define IDR_MISSION_TOOLBAR             388
#define IDD_MOD_SETTINGS_DIALOG         390
#define IDR_DELETE_TREE_ITEM            392
#define IDD_NEW_DIR_DIALOG              393
#define IDB_BITMAP1                     394
#define IDC_SLIDER1                     1006
#define IDC_CONTRAST                    1006
#define IDC_BRIGHTNESS                  1007
#define IDC_GAMMA                       1008
#define IDC_LEFT                        1011
#define IDC_RIGHT                       1012
#define IDC_TOP                         1013
#define IDC_BOTTOM                      1014
#define IDC_LEFT2                       1015
#define IDC_WINDOW_NAME                 1015
#define IDC_LEFTMAP                     1023
#define IDC_TOPMAP                      1024
#define IDC_RIGHTMAP                    1025
#define IDC_BOTTOMMAP                   1026
#define IDC_HLEFTMAP                    1027
#define IDC_MAX                         1027
#define IDC_HTOPMAP                     1028
#define IDC_MIN                         1028
#define IDC_HRIGHTMAP                   1029
#define IDC_HBOTTOMMAP                  1030
#define IDC_STEP                        1030
#define IDC_WIDTH                       1031
#define IDC_HEIGHT                      1032
#define IDC_SELLEFTMAP                  1033
#define IDC_SELTOPMAP                   1034
#define IDC_SLEFTMAP                    1035
#define IDC_SELRIGHTMAP                 1035
#define IDC_STOPMAP                     1036
#define IDC_SELBOTTOMMAP                1036
#define IDC_SRIGHTMAP                   1037
#define IDC_POSITION                    1037
#define IDC_SBOTTOMMAP                  1038
#define IDC_CHECK_ICON                  1039
#define IDC_CHECK_TEXT                  1040
#define IDC_CAPTION_TEXT                1041
#define IDC_LEFT_RADIO                  1042
#define IDC_HCENTER_RADIO               1043
#define IDC_RIGHT_RADIO                 1044
#define IDC_TOP_RADIO                   1045
#define IDC_COLOR_BUTTON                1045
#define IDC_VCENTER_RADIO               1046
#define IDC_SPECULAR_BUTTON             1046
#define IDC_BOTTOM_RADIO                1047
#define IDC_TEXT_COLOR_BUTTON           1048
#define IDC_CHECK_VERTICAL              1055
#define IDC_TEXTURE_TREE                1067
#define IDC_ICON_RADIO                  1068
#define IDC_TEXT_RADIO                  1069
#define IDC_COLUMN_LIST                 1069
#define IDC_ICONTEXT_RADIO              1070
#define IDC_SPACE_LEFT                  1071
#define IDC_SPACE_TOP                   1072
#define IDC_COLUMN_WIDTH                1073
#define IDC_VERTICAL_SPACE              1074
#define IDC_HORIZONTAL_SPACE            1075
#define IDC_ITEM_HEIGHT                 1076
#define IDC_WINDOWTYPE_COMBO            1077
#define IDC_EDIT_TEMPLATE_BUTTON        1078
#define IDC_SCROLLBAR_WIDTH             1079
#define IDC_COLUMNS_NUMBER              1080
#define IDC_LEFT_SCROLLBAR_CHECK        1081
#define IDC_SCROLLBAR_ALWAYS_CHECK      1082
#define IDC_EDITLEFT                    1083
#define IDC_EDITBOTTOM                  1086
#define IDC_EDITTOP                     1087
#define IDC_EDITRIGHT                   1088
#define IDC_BUTTON1                     1089
#define IDC_MOD_EXPORT_BTN              1089
#define IDC_BUTTON4                     1090
#define IDC_BUTTON5                     1091
#define IDC_REFERENCE_LIST              1092
#define IDC_RADIO1                      1094
#define IDC_ROAD                        1094
#define IDC_RADIO4                      1094
#define IDC_COMBO1                      1095
#define IDC_RADIO2                      1096
#define IDC_FENCE                       1096
#define IDC_RADIO5                      1096
#define IDC_LIST2                       1100
#define IDC_COMBO2                      1101
#define IDC_LIST1                       1102
#define IDC_MULTY_LIST                  1102
#define IDC_LIST3                       1103
#define IDC_CHECK2                      1104
#define IDC_OPEN_AND_SAVE               1104
#define IDC_CHECK3                      1105
#define IDC_CHECK4                      1106
#define IDC_CHECK5                      1107
#define IDC_CHECK6                      1108
#define IDC_CHECK7                      1109
#define IDC_CHECK8                      1110
#define IDC_CHECK9                      1111
#define IDC_CHECK1                      1112
#define IDC_FORCE_MODE_CHECK            1112
#define IDC_CONFIG_FOR_CURRENT_PROJECT_ONLY 1112
#define IDC_CHECK10                     1113
#define IDC_CHECK11                     1114
#define IDC_STATIC2                     1117
#define IDC_EDIT1                       1118
#define IDC_EDIT_BRIGHTNESS             1118
#define IDC_EDIT_COMMAND                1118
#define IDC_MOD_EXPORT_TEXT             1118
#define IDC_NAME_EDIT                   1118
#define IDC_EDIT2                       1119
#define IDC_EDIT_CONTRAST               1119
#define IDC_MOD_NAME_TEXT               1119
#define IDC_EDIT3                       1120
#define IDC_EDIT_GAMMA                  1120
#define IDC_MOD_VERSION_TEXT            1120
#define IDC_BROWSE_SOURCE_DIR           1121
#define IDC_EDIT26                      1121
#define IDC_BROWSE_DEST_DIR             1122
#define IDC_EDIT27                      1122
#define IDC_EDIT_SOURCE_DIR             1123
#define IDC_EDIT28                      1123
#define IDC_EDIT_DEST_DIR               1124
#define IDC_EDIT29                      1124
#define IDC_BUTTON2                     1125
#define IDC_EDIT_SEARCH_MASK            1125
#define IDC_EDIT_EXEC_DIR               1125
#define IDC_MOD_DEFAULTS_BTN            1125
#define IDC_TREE1                       1126
#define IDC_BROWSE_EXEC_DIR             1126
#define IDC_RADIO3                      1128
#define IDC_SPIN1                       1129
#define IDC_BATCH_MODE_PROGRESS         1132
#define IDC_PROGRESS_DIALOG_STATIC      1133
#define IDC_SLIDER2                     1134
#define IDC_SLIDER3                     1135
#define IDC_RADIO6                      1135
#define IDC_SLIDER4                     1136
#define IDC_STATIC100                   1136
#define IDC_SLIDER5                     1137
#define IDC_STATIC101                   1137
#define IDC_SLIDER6                     1138
#define IDC_STATIC102                   1138
#define IDC_SLIDER7                     1139
#define IDC_STATIC103                   1139
#define IDC_SLIDER8                     1140
#define IDC_STATIC104                   1140
#define IDC_SLIDER9                     1141
#define IDC_STATIC105                   1141
#define IDC_STATIC106                   1142
#define IDC_STATIC107                   1143
#define IDC_BUTTONADDPASTEGROUP         1144
#define IDC_EDIT4                       1145
#define IDC_MINIMAP_VIEW                1145
#define IDC_MOD_DESC_TEXT               1145
#define IDC_MINIMAP_CLOSE               1146
#define IDC_MINIMAP_PARTY               1147
#define IDC_EDIT5                       1147
#define IDC_MINIMAP_LAYER_0             1148
#define IDC_EDIT7                       1148
#define IDC_MINIMAP_LAYER_1             1149
#define IDC_EDIT8                       1149
#define IDC_MINIMAP_LAYER_2             1150
#define IDC_EDIT9                       1150
#define IDC_MINIMAP_LAYER_3             1151
#define IDC_EDIT6                       1151
#define IDC_MINIMAP_LAYER_4             1152
#define IDC_EDIT10                      1152
#define IDC_MINIMAP_LAYER_5             1153
#define IDC_EDIT12                      1153
#define IDC_MINIMAP_PARTY_LABEL         1154
#define IDC_EDIT13                      1154
#define IDC_MINIMAP_UPDATE              1155
#define IDC_EDIT14                      1155
#define IDC_EDIT11                      1156
#define IDC_LEFT_IMAGE                  1156
#define IDC_EDIT15                      1157
#define IDC_RIGHT_IMAGE                 1157
#define IDC_EDIT17                      1158
#define IDC_EDIT18                      1159
#define ID_BROWSE                       1159
#define IDC_EDIT19                      1160
#define IDC_EDIT_FILE                   1160
#define IDC_EDIT16                      1161
#define IDC_EDIT20                      1162
#define IDC_EDIT22                      1163
#define IDC_EDIT23                      1164
#define IDC_EDIT24                      1165
#define IDC_EDIT21                      1166
#define IDC_EDIT25                      1167
#define IDC_BUTTON3                     1168
#define IDC_BUTTON_NEW_MOD              1168
#define IDC_BRIDGE_TRANSPARENCE         2000
#define IDC_BUILDING_TRANSPARENCE       2001
#define IDC_FENCE_TRANSPARENCE          2002
#define IDC_OBJECT_TRANSPARENCE         2003
#define ID_INDICATOR_COORDS             3007
#define ID_INDICATOR_CONTROL            3008
#define ID_INDICATOR_TILEPOS            3009
#define ID_INDICATOR_OBJECTTYPE         3010
#define IDD_DIALOGPROPERTIE             3190
#define ID_GUI_VIEW                     5007
#define ID_ANIMATION_VIEW               5008
#define ID_ADD_BUTTON                   32771
#define ID_VIEW_CONTROL_TOOLBAR         32772
#define ID_RUN_BUTTON                   32775
#define ID_ESCAPE                       32776
#define ID_STOP_BUTTON                  32777
#define ID_BUTTONPOPUPMENU_SETUSUALTEXTURE 32778
#define ID_SETDEFAULTTEXTURE            32779
#define ID_BUTTONPOPUPMENU_SETHIGHLIGHTEDTEXTURE 32780
#define ID_SETHIGHLIGHTEDTEXTURE        32781
#define ID_BUTTONPOPUPMENU_SETSELECTEDTEXTURE 32782
#define ID_SETSELECTEDTEXTURE           32783
#define ID_BUTTONPOPUPMENU_SETPOSITION  32784
#define ID_SETPOSITION                  32785
#define ID_ALIGNMENU_ALIGNLEFT          32786
#define ID_ALIGNLEFT                    32787
#define ID_ALIGNMENU_ALIGNTOP           32788
#define ID_ALIGNTOP                     32789
#define ID_ALIGNMENU_ALIGNRIGHT         32790
#define ID_ALIGNRIGHT                   32791
#define ID_ALIGNMENU_ALIGNBOTTOM        32792
#define ID_ALIGNBOTTOM                  32793
#define ID_ALIGNMENU_SETEQUALSIZE       32794
#define ID_SETEQUALSIZE                 32795
#define ID_CHECK_BUTTON_PROPERTIES      32795
#define ID_CHECK_BUTTON_STRING          32795
#define ID_PROPERTIES                   32796
#define ID_MINSCROLL_BUTTON_STRING      32796
#define ID_SHOW_PROPERTIES              32797
#define ID_MAXSCROLL_BUTTON_STRING      32797
#define ID_ALIGNMENU_CREATERADIOBUTTON  32798
#define ID_MENU_CREATENEWTEMPLATE       32799
#define ID_DELETE_TEMPLATE              32800
#define ID_TEMPLATE_PROPERTIES          32801
#define ID_FILE_LOAD                    32803
#define ID_SHOW_CONTROL_BAR             32804
#define ID_HELP_TESTBUTTON              32805
#define ID_TESTBUTTON                   32806
#define ID_COMPOSE_ANIM                 32807
#define ID_FILE_EXPORTPROJECT           32808
#define ID_FILE_EXPORTFILES             32809
#define ID_FILE_CREATENEWPROJECT        32810
#define ID_BUTTON32811                  32811
#define ID_FILE_SAVEPROJECTAS           32812
#define ID_FILE_LOADMAP                 32813
#define ID_FILE_SAVEMAP                 32814
#define ID_FILE_SAVE_PROJECT_AS         32814
#define ID_FILE_EXPORTTOPICTURE         32815
#define ID_FILE_IMPORTFROMPICTURE       32816
#define ID_FILE_CLOSEPROJECT            32817
#define ID_BUTTONFILLAREA               32821
#define ID_INSERTTREEITEM_INSERTITEM    32823
#define ID_INSERT_TREE_ITEM             32824
#define ID_INTERPOLATE_TREE_ITEM        32825
#define ID_MOVE_OBJECT                  32826
#define ID_DRAW_GRID                    32827
#define ID_SET_ZERO_BUTTON              32828
#define ID_BUTTONUPDATE                 32829
#define ID_BUTTONFOG                    32831
#define ID_FILE_OPENOLDPROJECT          32832
#define ID_FILE_NEWMAP                  32833
#define ID_FILE_SETDIRECTORIES          32835
#define ID_FILE_SAVEMAP2                -32700
#define ID_FILE_BATCH_MODE              32837
#define ID_FILE_EXPORT_ONLY_RPG_STATS   32838
#define ID_TOOLS_CLEARCASH              32839
#define ID_KEYFRAMEZOOMMENU_ZOOMINX     32840
#define ID_KEYFRAME_ZOOMINX             32841
#define ID_KEYFRAME_ZOOMOUTX            32842
#define ID_KEYFRAME_ZOOMINY             32843
#define ID_KEYFRAME_ZOOMOUTY            32844
#define ID_DELETE_NODE                  32845
#define ID_RESET                        32846
#define ID_                             32847
#define ID_KEYFRAME_DELETE_NODE         32848
#define ID_KEYFRAME_RESET_ALL           32849
#define ID_GET_PARTICLE_INFO            32850
#define ID_EDIT_SETBACKGROUNDCOLOR      32851
#define ID_BUTTON_CAMERA                32852
#define ID_BUTTONAI                     32854
#define ID_BUTTONFIT                    32856
#define ID_BUTTON32858                  32858
#define ID_BUTTONADDTOGROUP             32859
#define ID_BUTTOSHOWINFO                32859
#define ID_SET_ENTRANCE_BUTTON          32860
#define ID_TOOLS_DELR                   32861
#define ID_DELETEELEMENT                32862
#define ID_CREATENEWTEMPLATE            32863
#define ID_CENTER_TILE                  32864
#define ID_FENCE_CENTER_ABOUT_TILE      32865
#define ID_CENTER_FENCE_ABOUT_TILE      32867
#define ID_BUTTONSHOWBOXES              32868
#define ID_SET_SHOOT_POINT              32869
#define ID_SET_SHOOT_ANGLE              32870
#define ID_SET_HORIZONTAL_SHOOT         32871
#define ID_OPTIONS                      32872
#define ID_BUTTONSETCAMERA              32873
#define ID_DRAW_TRANSPARENCE            32874
#define ID_DROPARROW                    32875
#define ID_DRAW_ONE_WAY_PASSABILITY     32875
#define ID_WINDOW_SHOWADVANCEDCLIPBOARD 32876
#define ID_BUTTONSHOWADVANCEDCLIPBOARD  32877
#define ID_DRAW_PASS                    32878
#define ID_SHOWOPTIONS                  32879
#define ID_DRAW_ONE_WAY_TRANSEPARENCE   32880
#define ID_SHOWMINIMAP                  32881
#define ID_SHOW_FIRE_RANGE              32882
#define ID_IMPORT_XML_FILE              32883
#define ID_SHOW_LOCATORS_INFO           32885
#define ID_EDIT_CROSSETS                32886
#define ID_BRIDGE_TRANSPARENCE          32910
#define ID_BUILDING_TRANSPARENCE        32911
#define ID_FENCE_TRANSPARENCE           32912
#define ID_OBJECT_TRANSPARENCE          32913
#define ID_IMPORT_CROSSETS              32914
#define ID_IMPORT_TERRAINS              32915
#define ID_SET_PICTURE_OPTIONS          32916
#define ID_SET_FIRE_POINT               32918
#define ID_SET_HORIZONTAL_FIRE          32920
#define ID_SET_FIRE_ANGLE               32921
#define ID_SET_FIRE_DIRECTION           32922
#define ID_MOVE_CURRENT_MODE            32923
#define ID_MOVE_POINT                   32924
#define ID_SET_DIRECTION_EXPLOSION      32925
#define ID_SET_SMOKE_POINT              32926
#define ID_GENERATE_POINTS              32930
#define ID_IMPORT_ACK_FILE              32932
#define ID_EXPORT_ACK_FILE              32933
#define ID_SWITCH_WIREFRAME             32934
#define ID_FILE_RECENT_FILES            32935
#define ID_SHOW_CROSSES                 32945
#define ID_PARTICLE_SOURCE              32947
#define ID_VIEW_ADVANCED_TOOLBAR        32949
#define ID_GENERATE_IMAGE               32957
#define ID_EXPORT_PAK                   32957
#define ID_RUN_GAME                     32959
#define ID_SHOW_TREE                    32960
#define ID_SHOW_OBJECT_INSPECTOR        32961
#define ID_SHOW_DIRECTION_BUTTON        32962
#define ID_SHOW_FUNCTION                32963
#define ID_MOD_SETTINGS                 32965
#define ID_EDITORS_UNITEDITOR           32966
#define ID_EDITORS_INFANTRYEDITOR       32967
#define ID_EDITORS_SQUADEDITOR          32968
#define ID_EDITORS_WEAPONEDITOR         32969
#define ID_EDITORS_MINEEDITOR           32970
#define ID_EDITORS_PARTICLEEDITOR       32971
#define ID_EDITORS_SPRITEEDITOR         32972
#define ID_EDITORS_EFFECTEDITOR         32973
#define ID_EDITORS_BUILDINGEDITOR       32975
#define ID_EDITORS_OBJECTEDITOR         32976
#define ID_EDITORS_FENCEEDITOR          32977
#define ID_EDITORS_BRIDGEEDITOR         32978
#define ID_EDITORS_TRENCHEDITOR         32979
#define ID_EDITORS_MISSIONEDITOR        32980
#define ID_EDITORS_CHAPTEREDITOR        32981
#define ID_EDITORS_CAMPAIGNEDITOR       32982
#define ID_EDITORS_MEDALEDITOR          32983
#define ID_EDITORS_TERRAINEDITOR        32984
#define ID_EDITORS_ROADEDITOR           32985
#define ID_EDITORS_RIVEREDITOR          32986
#define ID_TOOLS_SAVEMAPOBJECTS         32987
#define ID_MENU_DELETE_TREE_ITEM        32988
#define ID_VIEW_EXPANDALL               32989
#define ID_FILE_RECENT_0                32994
#define ID_FILE_RECENT_1                32995
#define ID_FILE_RECENT_2                32996
#define ID_FILE_RECENT_3                32997
#define ID_FILE_RECENT_4                32998
#define ID_FILE_RECENT_5                32999
#define ID_FILE_RECENT_6                33000
#define IDS_ERR_DIR_PREFIX              61216
#define ID_BRUSH                        61217
#define ID_IFGRIDBUTTON                 61218
#define ID_SHOW_FIRE_RANGE_FILTER       61219
#define IDC_SHORTCUTBAR                 61849

#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        395
#define _APS_NEXT_COMMAND_VALUE         32995
#define _APS_NEXT_CONTROL_VALUE         1161
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
