/* Generated by Together */

#ifndef CMANUVERGORKA_H
#define CMANUVERGORKA_H

#include "CManuver.h"
#include "IPlanePathFraction.h"

interface IPlane;
class CManuverGorka : public CManuver 
{
	CPtr<IPathFraction> pPath;
	CPtr<IPlane> pPlane;

	float fProgress;															// path progress
	float fZ;
	float fSpeed;
public:
	CManuverGorka() {  }
	
	void Init( interface IPlane *pPos );
	virtual CVec3 STDCALL GetPos() const;
	virtual CVec3 STDCALL GetSpeed() const;
	
	virtual bool STDCALL Advance();
};
#endif //CMANUVERGORKA_H