/* Generated by Together */

#ifndef CMANUVERBOEVOYZAHOD_H
#define CMANUVERBOEVOYZAHOD_H

#include "CManuver.h"
#include "IPlanePathFraction.h"

interface IPlane;
class CManuverBoevoyZahod : public CManuver 
{
	CPtr<IPathFraction> pPath;
	CPtr<IPlane> pPlane;

	float fProgress;															// path progress
	float fZ;
	float fSpeed;
public:
	CManuverBoevoyZahod() {  }
	
	void Init( interface IPlane *pPos, const IPlane * pEnemy );
	virtual CVec3 STDCALL GetPos() const;
	virtual CVec3 STDCALL GetSpeed() const;
	
	virtual bool STDCALL Advance();
	
};

#endif //CMANUVERBOEVOYZAHOD_H