/* Generated by Together */

#ifndef CPLANEPREFERENCES_H
#define CPLANEPREFERENCES_H

/**
 * 1) У самолета есть список маневров, которые он может совершать (с весами).
 * при выборе маневра CManuverBuilder смотрит в этот список и выбирает нужный маневр.
 * 2) у самолета есть параметры для определения того, что скорость малая...предельная, для.
 * 3) содержит в себе нечеткую логику самолета.
 */
class CPlanePreferences 
{

	float fMaxSpeed;
	float fStallSpeed;
public:

	void Init( const float _fMaxSpeed )
	{
		fMaxSpeed = _fMaxSpeed;
		fStallSpeed = _fMaxSpeed / 5.0f;
	}
	
	float GetR( const float fSpeed ) const { return 300.0f; }
	float GetStallSpeed() const { return fStallSpeed; }
	float GetMaxSpeed() const { return fMaxSpeed; }
};
#endif //CPLANEPREFERENCES_H