/* Generated by Together */

#ifndef IMANUVER_H
#define IMANUVER_H


extern float g;
/**
 * у кажддого маневра есть ID.
 * @interface
 */
interface IManuver : public IRefCount
{
	virtual CVec3 STDCALL GetPos() const = 0;
	virtual CVec3 STDCALL GetSpeed() const = 0;
	virtual CVec3 STDCALL GetNormale() const = 0;
	virtual CVec3 STDCALL GetTopDirection() const = 0;

	virtual bool STDCALL Advance( const NTimer::STime timeDiff ) = 0;

	virtual CVec3 GetProspectivePoint( const float fT ) const = 0;
	
	virtual void Init( const enum EManuverDestination dest, interface IPlane *pPlane, interface IPlane *pEnemy = 0 ) { NI_ASSERT_T(false,"WRONG CALL");}


	virtual const CVec3 STDCALL GetEndPoint() const = 0;
};
#endif //IMANUVER_H